<?php
    $array = array();
    $data = array();
    echo "[";
    foreach ($list_block as $key => $value){
        $namecode = $value["name_code"];
        $t = "";
        if($key > 0){
            $t = ',';
        }
        echo $t.''.$namecode.'":';
        if($value["id_block"] < 123){
            $this->$namecode(array(
                "adapter" => $adapter,
                "active" => $active,
                "id_block_page" => $value["id"]
            ));
        }else{
            $this->blockfull(array(
                "adapter" => $adapter,
                "active" => $active,
                "id_block_page" => $value["id"]
            ));
        }
        echo '}';
    }
    echo "]";
?>