
<link rel="stylesheet" href="http://test.jpe.vn/admins/assets/plugins/css/slick.css">


<link href="<?php echo URL_ASSET?>frontend/assets/css/homeCustom.css" rel="stylesheet" type="text/css" />

<!--START header-->
<?php
$this->header(array(
    "adapter" => $adapter,
    "active" => $active
));

?>
<!--END header-->

<div class="slider slick-initialized slick-slider slick-dotted">
    <div class="slick-list draggable">
        <div class="slick-track" style="opacity: 1; width: 5988px;">
            <div
                    class="slick-slide"
                    data-slick-index="0"
                    aria-hidden="true"
                    style="width: 1497px; position: relative; left: 0px; top: 0px; z-index: 998; opacity: 0; transition: opacity 1000ms linear 0s;"
                    role="tabpanel"
                    id="slick-slide10"
                    tabindex="-1"
            >
                <div>
                    <div data-title="Săn sale 8.8" class="item" style="width: 100%; display: inline-block;">
                        <a href="" title="Săn sale 8.8" tabindex="-1"><img id="imageid" src="http://test.jpe.vn/uploads/files/1006%20%5BConverted%5D-03.png" alt="Săn sale 8.8" /></a>
                    </div>
                </div>
            </div>
            <div
                    class="slick-slide"
                    data-slick-index="1"
                    aria-hidden="true"
                    style="width: 1497px; position: relative; left: -1497px; top: 0px; z-index: 998; opacity: 0; transition: opacity 1000ms linear 0s;"
                    role="tabpanel"
                    id="slick-slide11"
                    tabindex="-1"
            >
                <div>
                    <div data-title="Flash sale" class="item" style="width: 100%; display: inline-block;">
                        <a href="http://test.jpe.vn/" title="Flash sale" tabindex="-1"><img id="imageid" src="http://test.jpe.vn/uploads/files/1%20(2).png" alt="Flash sale" /></a>
                    </div>
                </div>
            </div>
            <div
                    class="slick-slide"
                    data-slick-index="2"
                    aria-hidden="true"
                    style="width: 1497px; position: relative; left: -2994px; top: 0px; z-index: 998; opacity: 0; transition: opacity 1000ms linear 0s;"
                    role="tabpanel"
                    id="slick-slide12"
                    tabindex="-1"
            >
                <div>
                    <div data-title="Deal hot" class="item" style="width: 100%; display: inline-block;">
                        <a href="http://test.jpe.vn/" title="Deal hot" tabindex="-1"><img id="imageid" src="http://test.jpe.vn/uploads/files/1%20(3).png" alt="Deal hot" /></a>
                    </div>
                </div>
            </div>
            <div class="slick-slide slick-current slick-active" data-slick-index="3" aria-hidden="false" style="width: 1497px; position: relative; left: -4491px; top: 0px; z-index: 999; opacity: 1;" role="tabpanel" id="slick-slide13">
                <div>
                    <div data-title="Da đẹp sáng khỏe" class="item" style="width: 100%; display: inline-block;">
                        <a href="" title="Da đẹp sáng khỏe" tabindex="0"><img id="imageid" src="http://test.jpe.vn/uploads/files/1%20(4).png" alt="Da đẹp sáng khỏe" /></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <ul class="slick-dots" style="" role="tablist">
        <li class="" role="presentation"><span title="Săn sale 8.8"> Săn sale 8.8 </span></li>
        <li role="presentation" class=""><span title="Flash sale"> Flash sale </span></li>
        <li role="presentation" class=""><span title="Deal hot"> Deal hot </span></li>
        <li role="presentation" class="slick-active"><span title="Da đẹp sáng khỏe"> Da đẹp sáng khỏe </span></li>
    </ul>
</div>

<div  class="container">
    <div  class="list-banner">
        <div  class="item">
            <a  href="" title=""><img  src="http://test.jpe.vn/uploads/files/banner-dotuoi-04.png" alt="" /></a>
        </div>
        <div  class="item">
            <a  href="" title=""><img  src="http://test.jpe.vn/uploads/files/banner-dotuoi-05.png" alt="" /></a>
        </div>
        <div  class="item">
            <a  href="" title=""><img  src="http://test.jpe.vn/uploads/files/banner-dotuoi-06.png" alt="" /></a>
        </div>
        <div  class="item">
            <a  href="" title=""><img  src="http://test.jpe.vn/uploads/files/banner-dotuoi-07.png" alt="" /></a>
        </div>
    </div>
</div>

<div  class="container">
    <div  class="list-banner">
        <div  class="item">
            <a  href="" title=""><img  src="http://test.jpe.vn/uploads/files/banner-dotuoi-02(1).png" alt="" /></a>
        </div>
        <div  class="item">
            <a  href="" title=""><img  src="http://test.jpe.vn/uploads/files/banner-dotuoi-03(1).png" alt="" /></a>
        </div>
    </div>
</div>


<div class="container">
    <div class="row">
        <div class="col-12 banner-product">
            <div>
                <a href="" title=""><img src="uploads/files/1110x600.png" alt="" /></a>
            </div>
        </div>
        <div class="col-12 tab-product">
            <div class="card">
                <ul class="card-header">
                    <li><button class="active btn btn-circle-1">Tất cả</button></li>
                    <li><button class="btn btn-circle-1">Colagen dạng nước</button></li>
                    <li><button class="btn btn-circle-1">Colagen dạng viên</button></li>
                    <li><button class="btn btn-circle-1">Collagen dạng bột</button></li>
                </ul>
                <div class="card-body">
                    <div class="list-product">
                        <div  class="item">
                            <div  class="box-img">
                                <a  href="http://test.jpe.vn/vien-uong-collagen-the-fancys-max-taiyou-27000mg-90-vien" title="Viên uống Collagen The Fancy’s Max Taiyou 27.000mg 90 viên">
                                    <img  src="http://test.jpe.vn/uploads/files/DanhMuc/SanPham/vien%20uong%20trang%201.jpeg" alt="Viên uống Collagen The Fancy’s Max Taiyou 27.000mg 90 viên" />
                                </a>
                            </div>
                            <div  class="detail">
                                <h3  class="title">
                                    <a  href="http://test.jpe.vn/vien-uong-collagen-the-fancys-max-taiyou-27000mg-90-vien" title="Viên uống Collagen The Fancy’s Max Taiyou 27.000mg 90 viên">
                                        Viên uống Collagen The Fancy’s Max Taiyou 27.000mg 90 viên
                                    </a>
                                </h3>
                                <ul  class="box-price">
                                    <li  class="price">850,000 đ</li>
                                    <li  class="old-price">1,000,000 đ</li>
                                </ul>
                            </div>
                            <!-- <div  class="action">
                                <ul >
                                    <li >
                                        <a  href="http://test.jpe.vn/vien-uong-collagen-the-fancys-max-taiyou-27000mg-90-vien" title="Chi tiết" class="btn  btn-chitiet-custom d-flex align-items-center justify-content-center">
                                            Chi tiết
                                        </a>
                                    </li>
                                    <li >
                                        <button  class="btn btn-muangay-custom d-flex align-items-center justify-content-center"><span >MUA NGAY</span></button>
                                    </li>
                                </ul>
                            </div> -->
                        </div>

                    </div>
                </div>
                <div class="card-footer"><!----></div>
            </div>
        </div>
    </div>
    <!---->
</div>


<div class="container">
    <div class="row">
        <div class="col-12 banner-product">
            <div>
                <a href="" title=""><img src="uploads/files/DanhMuc/Slider/thiet-ke-banner-dep-cho-quang-cao-web-thoi-trang-1.jpeg" alt="" /></a>
            </div>
        </div>
        <div class="col-12 tab-product">
            <div class="card">
                <ul class="card-header">
                    <li><button class="active btn btn-circle-1">Tất cả</button></li>
                    <li><button class="btn btn-circle-1">Thời trang nam</button></li>
                    <li><button class="btn btn-circle-1">Thời trang nữ</button></li>
                    <li><button class="btn btn-circle-1">Thời trang bé trai</button></li>
                </ul>
                <div class="card-body">
                    <div class="list-product">

                        <div  class="item">
                            <div  class="box-img">
                                <a  href="http://test.jpe.vn/quan-jean-be-trai" title="Quần jean bé trai">
                                    <img  src="http://test.jpe.vn/uploads/files/DanhMuc/SanPham/2bp20s004-sj520-120.jpg" alt="Quần jean bé trai" />
                                </a>
                            </div>
                            <div  class="detail">
                                <h3  class="title"><a  href="http://test.jpe.vn/quan-jean-be-trai" title="Quần jean bé trai">Quần jean bé trai</a></h3>
                                <ul  class="box-price">
                                    <li  class="price">100,000 đ</li>
                                    <li  class="old-price">199,000 đ</li>
                                </ul>
                            </div>
                            <!-- <div  class="action">
                                <ul >
                                    <li ><a  href="http://test.jpe.vn/quan-jean-be-trai" title="Chi tiết" class="btn btn-chitiet-custom d-flex align-items-center justify-content-center">Chi tiết</a></li>
                                    <li >
                                        <button  class="btn btn-muangay-custom d-flex align-items-center justify-content-center"><span >MUA NGAY</span></button>
                                    </li>
                                </ul>
                            </div> -->
                        </div>


                    </div>
                </div>
                <div class="card-footer"><!----></div>
            </div>
        </div>
    </div>
    <!---->
</div>












<!--START footer-->
<?php
$this->footer(array("adapter" => $adapter));
?>
<!--END footer-->