<link href="<?php echo URL_ASSET?>frontend/assets/css/product3Column.css" rel="stylesheet" type="text/css" />
<div class="product-cate">
    <h2 class="title-filter">
        <?php echo $arrayParam["name_vi"];?> 
        <span>(<?php echo $arrayParam["count"];?> sản phẩm)</span>
    </h2>
    <input name="order" id="order" value="<?php echo $arrayParam['order']?>" type="hidden">
    <input name="sale" id="sale" value="<?php echo $arrayParam['sale'];?>" type="hidden">
    <ul class="list-filter">
        <li>Sắp xếp theo: </li>
        <li><a href="javascript:order('sortincat asc');" title="Mặc định" class="<?php if(($arrayParam['order']=="sortincat asc" || $arrayParam['order'] == 'id asc') && $arrayParam['sale']=="") {?>active<?php }?> btn-circle-1">Mặc định</a></li>
        <li><a href="javascript:order('price desc');" title="Giá cao" class="<?php if(($arrayParam['order'])=="price desc" && $arrayParam['sale']=="") {?>active<?php }?> btn-circle-1">Giá cao</a></li>
        <li><a href="javascript:order('price asc');" title="Giá thấp" class="<?php if(($arrayParam['order'])=="price asc" && $arrayParam['sale']=="") {?>active<?php }?> btn-circle-1">Giá thấp</a></li>
        <li><a href="javascript:order('name_vi asc');" title="A-z" class="<?php if(($arrayParam['order'])=="name_vi asc" && $arrayParam['sale']=="") {?>active<?php }?> btn-circle-1">A-z</a></li>
        <li><a href="javascript:sale('2');" title="Sale" class="<?php if(($arrayParam['sale'])=="2") {?>active<?php }?> btn-circle-1">Sale</a></li>
    </ul>
    <div itemscope itemtype="http://schema.org/Product" class="list-product">
        <div itemprop="aggregateRating" itemtype="http://schema.org/AggregateRating" itemscope style="display: none">
            <meta itemprop="reviewCount" content="89" />
            <meta itemprop="ratingValue" content="4.4" />
        </div>
        <?php if(!empty($list)){
            foreach ($list as $value){
                $price_promotion = "";
                $hienthi = 0;
                $text_qt = "";
                $images_qt = "";
                if( $value["status_product"] == 1 && strtotime($value["date_start"]) <= strtotime(date("y-m-d")) && strtotime($value["date_end"]) >= strtotime(date("y-m-d"))){
                    if(!empty($value["text_pt"])){
                        $price_promotion = $value["price"] - ($value["text_pt"]*$value["price"]/100);
                        $hienthi = 1;
                    }
                    if(!empty($value["text_vnd"])){
                        $price_promotion = $value["price"] - $value["text_vnd"];
                        $hienthi = 1;
                    }
                }
                if(!empty($value["images"])){
                    $array = explode("-", $value["images"]);
                    $time = date("Y/m/d",$array[0])."/";
                    $images = PATH_IMAGE_PRO.$time."268x268-".$value["images"];
                }else{
                    $images = "";
                }
                $url = URL.$value["slug_vi"]."-sp-" . $value["id"];
                $price = number_format($value["price"],"0",",",".");
        ?>
        <div class="item item-product-custom">
            <div class="box-img">
                <a href="<?php echo $url;?>" title="<?php echo $value["name_vi"];?>">
                    <img itemprop="image" src="<?php echo $images;?>" alt="<?php echo $value["name_vi"];?>">
                </a>
                <?php if( $value["status_product"] == 1 && strtotime($value["date_start"]) <= strtotime(date("y-m-d")) && strtotime($value["date_end"]) >= strtotime(date("y-m-d"))){ ?>
                    <?php if(!empty($value["text_pt"])){?>
                        <div class="block-sale">
                            <img alt="<?php echo $value["text_pt"]?>" src="<?php echo $km_images;?>">
                            <span class="sale">-<?php echo $value["text_pt"]?>%</span>
                        </div>
                    <?php }?>
                    <?php if(!empty($value["text_qt"])){?>
                        <div class="block-sale2">
                            <img alt="<?php echo $km_images_qt;?>" src="<?php echo $km_images_qt;?>">
                        </div>
                        <?php 
                            $text_qt = $value["text_qt"];
                            $images_qt = $km_images_qt;
                        ?>
                    <?php }?>
                <?php }?>
                <?php if($value["status_product_k"] == 1 && strtotime($value["date_start_k"]) <= strtotime(date("y-m-d")) && strtotime($value["date_end_k"]) >= strtotime(date("y-m-d"))){?>
                    <?php if(!empty($list_product[$value["id"]])){?>
                        <div class="block-sale3">
                            <img alt="<?php echo $list_product[$value["id"]];?>" src="<?php echo $list_product[$value["id"]];?>">
                        </div>
                    <?php }?>
                <?php }?>
            </div>
            <div class="detail">
                <meta itemprop="mpn" content="<?php echo $value["sku"];?>" />
                <meta itemprop="sku" content="<?php echo $value["sku"];?>" />
                <div itemprop="description" style="display:none;"><?php echo $value["notes_vi"];?></div>
                <h3 class="title">
                    <a itemprop="name" href="<?php echo $url;?>" title="<?php echo $value["name_vi"];?>"><?php echo $value["name_vi"];?></a>
                </h3>
                <div itemprop="review" itemtype="http://schema.org/Review" itemscope>
                    <div itemprop="author" itemtype="http://schema.org/Person" itemscope>
                        <meta itemprop="name" content="Japana" />
                    </div>
                    <div itemprop="reviewRating" itemtype="http://schema.org/Rating" itemscope>
                        <meta itemprop="ratingValue" content="4" />
                        <meta itemprop="bestRating" content="5" />
                    </div>
                </div>
                <div itemprop="brand" itemtype="http://schema.org/Thing" itemscope>
                    <meta itemprop="name" content="<?php echo $value["brand"];?>" />
                </div>
                <ul itemprop="offers" itemtype="http://schema.org/Offer" itemscope class="box-price">
                    <meta itemprop="priceCurrency" content="VND" />
                    <link itemprop="url" href="https://japana.vn<?php echo $_SERVER["REQUEST_URI"];?>" />
                    <meta itemprop="availability" content="https://schema.org/InStock" />
                    <meta itemprop="priceValidUntil" content="2020-11-05" />
                    <?php if(intval($hienthi) > 0){ ?>
                        <li class="price">
                            <span><?php echo number_format($price_promotion,"0",",",".");?> đ</span>
                        </li>
                        <li itemprop="price" class="price" style="display: none;">
                            <span><?php echo intval($price_promotion);?></span>
                        </li>
                        <li class="old-price">
                            <span><?php echo $price;?> đ</span>
                        </li>
                    <?php }else{ ?>
                        <li class="price"><span><?php echo $price;?> đ</span> </li>
                        <li itemprop="price" class="price" style="display: none;">
                            <span><?php echo $value["price"];?></span>
                        </li>
                    <?php } ?>
                </ul>
            </div>

        </div>
        <?php }
            }else{?>
            <meta itemprop="mpn" content="<?php echo $arrayParam["id_brand"]; ?>" />
            <meta itemprop="name" content="<?php echo $arrayParam["name_vi"]; ?>" />
            <link itemprop="image" href="https://japana.vn/assets/admin/ngonguyen/images/no-img.png" />
            <meta itemprop="description" content="<?php echo $arrayParam["name_vi"]; ?>" />
            <div itemprop="offers" itemtype="http://schema.org/Offer" itemscope>
                <link itemprop="url" href="<?php echo $arrayParam["url"]; ?>" />
                <meta itemprop="availability" content="https://schema.org/InStock" />
                <meta itemprop="priceCurrency" content="VND" />
                <meta itemprop="itemCondition" content="https://schema.org/UsedCondition" />
                <meta itemprop="price" content="0" />
                <meta itemprop="priceValidUntil" content="2020-11-05" />
            </div>
            <div itemprop="review" itemtype="http://schema.org/Review" itemscope>
                <div itemprop="author" itemtype="http://schema.org/Person" itemscope>
                    <meta itemprop="name" content="Japana" />
                </div>
                <div itemprop="reviewRating" itemtype="http://schema.org/Rating" itemscope>
                    <meta itemprop="ratingValue" content="4" />
                    <meta itemprop="bestRating" content="5" />
                </div>
            </div>
            <meta itemprop="sku" content="<?php echo $arrayParam["id_brand"]; ?>" />
            <div itemprop="brand" itemtype="http://schema.org/Thing" itemscope>
                <meta itemprop="name" content="<?php echo $arrayParam["name_vi"]; ?>" />
            </div>
        <?php } ?>
    </div>
    <?php
        if(isset($paginator)){
            echo $this->paginationControl($paginator, 'Sliding', 'view/frontend/pagination', $params = array('arrayParam' => $arrayParam));
        }
    ?>
</div>
<script>
    function order(id) {
        jQuery("#sale").val('');
        jQuery("#order").val(id);
        jQuery("#filter_from").submit()
    }
    function sale(id){
        jQuery("#order").val('');
    	jQuery("#sale").val(id);
    	jQuery("#filter_from").submit();
    }
</script>

<script type="text/javascript" src="//static.criteo.net/js/ld/ld.js" async="true"></script>
<script type="text/javascript">
    window.criteo_q = window.criteo_q || [];
    window.criteo_q.push(
        { event: "setAccount", account: 72566 },
        { event: "setEmail", email: "marketing@japana.vn" },
        { event: "setSiteType", type: "d" },
        { event: "viewList", item:[ <?php foreach ($list as $value){
                echo '"'.$value['id'].'"'.",";
            } ?> ]}
    );
</script>