<?php
if(!empty($config["og_image"])){
    $array = explode("-", $config["og_image"]);
    $time = date("Y/m/d", $array[0]) . "/";
    $url_image = PATH_IMAGE_PRO . $time . $config["og_image"];
    $url = getimagesize($url_image);
    if (!is_array($url)) {
        $array = explode("-", $config["images"]);
        $time = date("Y/m/d", $array[0]) . "/";
        $url_image = PATH_IMAGE_PRO . $time . $config["images"];
    }
}elseif(!empty($config["images"])){
    $array = explode("-", $config["images"]);
    $time = date("Y/m/d", $array[0]) . "/";
    $url_image = PATH_IMAGE_PRO . $time . $config["images"];
}
$this->headTitle ($config["meta_web_title"]);
$this->headMeta ()
    ->appendName ( 'keywords',      $config["meta_web_keyword"])
    ->appendName ( 'description',   $config["meta_web_desc"])
    ->setProperty('fb:app_id',       "626517987552557")
    ->setProperty('og:url',         $config["url"])
    ->setProperty("og:type", "product")
    ->setProperty('og:title',       $config["og_title"])
    ->setProperty('og:locale',       "vi_VN")
    ->setProperty('og:site_name',       "japana.vn")
    ->setProperty('og:image',       $url_image)
    ->setProperty('og:image:secure_url',$url_image)
    ->setProperty('og:image:width',       "600")
    ->setProperty('og:image:height',       "600")
    ->setProperty('og:description', $config["og_desc"]);
$this->headLink(array('rel' => 'canonical', 'href' => $config["url"]));
?>
<?php

$breadcrumb_detail = "";
$product1_column1 = array();
$key = array_search('product1_column1', array_column($list_block, 'name_code'));

if ($key) {
    $product1_column1['config'] = $list_block[$key];
    unset($list_block[$key]);
    $customeConfig = array(
        "adapter"    => $adapter,
        "active"    => $active,
        "id"         => $arrayParam["id"],
        "url"         => $config["url"],
        "config"         => $config,
        "arrayParam"  => $arrayParam,
        "list"       => $list,
        "list_id_category" => $config["list_id_category"],
        "breadcrumb" => $breadcrumb_detail
    );
    $product1_column1['template'] = $customeConfig;
}

    foreach ($list_block as $key => $value){
        if(!empty($breadcrumb_slug)){
            $limiddle = '<li><a href="'. URL.$breadcrumb_slug.'/"'. 'title="'. $breadcrumb.'">'. $breadcrumb.' /</a></li>';
            $breadcrumb_detail = $breadcrumb;
        }else{
            $limiddle = '';
        }
        
        if(!empty($breadcrumb_slug1)){
            $limiddle1 = '<li><a href="'. URL.$breadcrumb_slug1.'/"'. 'title="'. $breadcrumb1.'">'. $breadcrumb1.' /</a></li>';
            $breadcrumb_detail = $breadcrumb1;
        }else{
            $limiddle1 = '';
        }

        if($key == 2){?>
            <div class="site-inner">
    			<div class="content-sidebar-wrap">
    				<main class="pro-detail content">
                        <div class="navigation">
                            <div class="container">
                                <ul>
                                    <li><a href="<?php echo URL ?>" title="Trang chủ">Trang chủ / </a></li>
                                    <?php echo $limiddle ?>
                                    <?php echo $limiddle1 ?>
                                    <li><?php echo $config["name_vi"] ?></li>
                                </ul>
                            </div>
                        </div>

        <?php }
        
        if($value["begin"] == 1){
            echo '<div class="container">';
        }

        $namecode = $value["name_code"];
        $customeConfig = array(
            "adapter"    => $adapter,
            "active"    => $active,
            "id"         => $arrayParam["id"],
            "url"         => $config["url"],
            "config"         => $config,
            "arrayParam"  => $arrayParam,
            "list"       => $list,
            "list_id_category" => $config["list_id_category"],
            "breadcrumb" => $breadcrumb_detail
        );
        if ($namecode === 'product_detail') {
            $customeConfig['product1_column1'] = $product1_column1;
        }
        $this->$namecode($customeConfig);

        if($value["end"] == 1){
            echo "</div>";
        }
        if($key == (count($list_block) - 2)){
            echo "</main></div></div>";
        }
    }
?>