<div class="news">
	<div class="container">
		<h3 class="title-news">Thông tin tiêu dùng</h3>
	</div>
	<div class="list-news">
		<div class="item">
			<div class="box-img">
				<a href="#" title="title">
					<img src="<?php echo URL;?>assets/images/news1.png" align="images">
					<span class="link-news"><i class="fa fa-eye" aria-hidden="true"></i></span>
				</a>
			</div>
			<div class="detail">
				<div class="time-tag">
					<span><i class="fa fa-calendar-o" aria-hidden="true"></i> Tháng 10, 2017</span>
				</div>
				<h3 class="title">
					<a href="#" title="title">Thực phẩm chức năng hỗ trợ điều trị ung thư</a>
				</h3>
				<div class="count-news">
					<span><i class="fa fa-comment" aria-hidden="true"></i> 80</span>
					<span><i class="fa fa-eye" aria-hidden="true"></i> 396</span>
				</div>
			</div>
		</div>
		<div class="item">
			<div class="box-img">
				<a href="#" title="title">
					<img src="<?php echo URL;?>assets/images/news2.png" align="images">
					<span class="link-news"><i class="fa fa-eye" aria-hidden="true"></i></span>
				</a>
			</div>
			<div class="detail">
				<div class="time-tag">
					<span><i class="fa fa-calendar-o" aria-hidden="true"></i> Tháng 10, 2017</span>
				</div>
				<h3 class="title">
					<a href="#" title="title">Thực phẩm chức năng hỗ trợ điều trị ung thư</a>
				</h3>
				<div class="count-news">
					<span><i class="fa fa-comment" aria-hidden="true"></i> 80</span>
					<span><i class="fa fa-eye" aria-hidden="true"></i> 396</span>
				</div>
			</div>
		</div>
		<div class="item">
			<div class="box-img">
				<a href="#" title="title">
					<img src="<?php echo URL;?>assets/images/news3.png" align="images">
					<span class="link-news"><i class="fa fa-eye" aria-hidden="true"></i></span>
				</a>
			</div>
			<div class="detail">
				<div class="time-tag">
					<span><i class="fa fa-calendar-o" aria-hidden="true"></i> Tháng 10, 2017</span>
				</div>
				<h3 class="title">
					<a href="#" title="title">Thực phẩm chức năng hỗ trợ điều trị ung thư</a>
				</h3>
				<div class="count-news">
					<span><i class="fa fa-comment" aria-hidden="true"></i> 80</span>
					<span><i class="fa fa-eye" aria-hidden="true"></i> 396</span>
				</div>
			</div>
		</div>
		<div class="item">
			<div class="box-img">
				<a href="#" title="title">
					<img src="<?php echo URL;?>assets/images/news4.png" align="images">
					<span class="link-news"><i class="fa fa-eye" aria-hidden="true"></i></span>
				</a>
			</div>
			<div class="detail">
				<div class="time-tag">
					<span><i class="fa fa-calendar-o" aria-hidden="true"></i> Tháng 10, 2017</span>
				</div>
				<h3 class="title">
					<a href="#" title="title">Thực phẩm chức năng hỗ trợ điều trị ung thư</a>
				</h3>
				<div class="count-news">
					<span><i class="fa fa-comment" aria-hidden="true"></i> 80</span>
					<span><i class="fa fa-eye" aria-hidden="true"></i> 396</span>
				</div>
			</div>
		</div>
		<div class="item">
			<div class="box-img">
				<a href="#" title="title">
					<img src="<?php echo URL;?>assets/images/news3.png" align="images">
					<span class="link-news"><i class="fa fa-eye" aria-hidden="true"></i></span>
				</a>
			</div>
			<div class="detail">
				<div class="time-tag">
					<span><i class="fa fa-calendar-o" aria-hidden="true"></i> Tháng 10, 2017</span>
				</div>
				<h3 class="title">
					<a href="#" title="title">Thực phẩm chức năng hỗ trợ điều trị ung thư</a>
				</h3>
				<div class="count-news">
					<span><i class="fa fa-comment" aria-hidden="true"></i> 80</span>
					<span><i class="fa fa-eye" aria-hidden="true"></i> 396</span>
				</div>
			</div>
		</div>
	</div>
</div>