<?php
$this->headTitle ('Tinh chất nhau thai Placenta 82x Sakura Premium 450000mg 500ml');
$this->headMeta ()
    ->appendName ( 'keywords',      '')
    ->appendName ( 'description',   'Placenta 82x Sakura Premium 450000mg phiên bản mới không chỉ mang trọn vẹn tinh hoa dưỡng nhan từ “siêu phẩm” Placenta 82x, nay còn được bổ sung các chiết xuất và thành phần mới như chiết xuất hoa anh đào, cam Nhật Bản, xoài châu Phi... giúp tinh chất này hỗ trợ cải thiện các nếp nhăn một cách nhanh chóng, dưỡng da săn chắc, mịn màng và trắng sáng, rạng ngời.')
    ->setProperty('og:image',       'https://japana.vn/uploads/product/2019/04/17/1555498925-um-450000mg-500ml-sieu-thi-nhat-ban-japana-23.jpeg')
    ->setProperty("og:type", "product")
    ->setProperty('fb:app_id',       "626517987552557")
    ->setProperty('og:image:secure_url',       'https://japana.vn/uploads/product/2019/04/17/1555498925-um-450000mg-500ml-sieu-thi-nhat-ban-japana-23.jpeg')
    ->setProperty('og:description', 'Placenta 82x Sakura Premium 450000mg phiên bản mới không chỉ mang trọn vẹn tinh hoa dưỡng nhan từ “siêu phẩm” Placenta 82x, nay còn được bổ sung các chiết xuất và thành phần mới như chiết xuất hoa anh đào, cam Nhật Bản, xoài châu Phi... giúp tinh chất này')
    ->setProperty('og:title',      'Tinh chất nhau thai Placenta 82x Sakura Premium 450000mg 500ml')
    ->setProperty('og:url',         'https://japana.vn/tinh-chat-nhau-thai-placenta-82x-sakura-premium-450000mg-500ml-sp-3763');
$this->headLink(array('rel' => 'canonical', 'href' => URL));
$this->header(array(
    "adapter" => $adapter,
    "active" => $active));
?>
<?php
    echo $detail["content"];
?>
<?php
$this->footer(array("adapter" => $adapter));
?>