

<?php 

    





?>
Xuất file excel

<form action="" method="post">

	<textarea style="width: 100%; height: 200px;" name="sql" rows="" cols=""><?php echo $sql;?></textarea>

	<button type="submit">Sumbmit</button>

</form>

<?php 
    if(!empty($list)){
        
        echo "<table>";
        foreach ($list as $val){
            echo '<tr>';
            foreach ($val as $v){
                echo '<td>'.$v.'</td>';
            }
            echo '</tr>';
        }
        echo "</table>";
        
    }
?>



