<?php if(!empty($list)){
    $t = 0;
    ?>
<div class="auto-search">
	<!-- 
	<?php if(!empty($list["category"]["data"])){ ?>
	<h3 class="title">Danh mục</h3>
	<ul class="cate-search">
		<?php
		$t = 1;
		foreach ($list["category"]["data"] as $key => $value){
		      $url = URL . $value["slug_vi"]."/";
		      
		    ?>
    		<li>
    			<a href="<?php echo $url;?>"
    			title="Làm Trắng Da/"><i class="fa fa-chevron-right"></i>
    				<?php echo $value["name_vi"]?>
    			</a>
    		</li>
    		<?php 
			 if($key == 4){
			     break;
			 }
			?>
		<?php }?>
	</ul>
	<hr>
	<?php }?>
	<?php if(!empty($list["brand"]["data"])){?>
	<div class="client-top">
		<h3 class="title">Thương hiệu</h3>
		<div class="box1">
			<?php
			$t = 1;
			foreach ($list["brand"]["data"] as $key => $value){?>
    				<?php
    				$url = URL."brand/".$value["slug_vi"]."/";
    				if(!empty($value["images"])){
        				$array = explode("-", $value["images"]);
        				$time = $array[0];
        				$folder_date = PATH_IMAGE_BRAND."/".$value["images"];
    				?>
    				<div class="item">
            			<a href="<?php echo $url;?>" title="<?php echo $value["name_vi"];?>">
            				<img src="<?php echo $folder_date;?>" alt="logo">
            			</a>
    				</div>
    				<?php }else{?>
        			<div class="item">
        				<a href="<?php echo $url;?>"
        					title="title">NO IMAGES</a>
        			</div>
        			<?php }?>
        			<?php
        			 if($key == 3){
        			     break;
        			 }
        			?>
			<?php }?>
		</div>
	</div>
	<hr>
	<?php }?>
	 -->
	<?php if(!empty($list["product"]["data"])){?>
	<div class="pro-top">
<!-- 		<h3 class="title">Sản phẩm</h3> -->
		<div style="margin-top: 15px;" class="list-pro-search">
			<?php
			$t = 1;
			foreach ($list["product"]["data"] as $key => $value){?>
				<?php 
				$folder_date = "";
				if(!empty($value["images"])){
				    $array = explode("-", $value["images"]);
				    $time = $array[0];
				    $folder_date = PATH_IMAGE_PRO."/".date('Y',$time)."/".date('m',$time)."/".date('d',$time)."/".$value["images"];
				}
                $price = "";
                $hienthi = 0;
                $pt = 0;$qt = "";
                if( $value["status_product"] == 1 && strtotime($value["date_start"]) <= strtotime(date("y-m-d")) && strtotime($value["date_end"]) >= strtotime(date("y-m-d"))){
                    if(!empty($value["text_pt"])){
                        $pt = $value["text_pt"];
                        $price = $value["price"] - ($value["text_pt"]*$value["price"]/100);
                        $hienthi = 1;
                    }
                    if(!empty($value["text_vnd"])){
                        $hienthi = 1;
                        $price = $value["price"] - $value["text_vnd"];
                    }
                    if(!empty($value["text_qt"])){
                        $qt = $value["text_qt"];
                    }
                }
                $url = URL . $value["slug_vi"] . "-sp-" . $value["id"];
                ?>
                <div class="item">
                    <div class="col-md-1 box-img nopadding">
                        <?php
                        if (!empty($value['images'])) { ?>
                            
                            <a href="<?php echo $url; ?>" title="title">
                                <img src="<?php echo $folder_date; ?>"
                                     alt="images">
                            </a>
                            <?php if(!empty($qt)){?>
                            <div class="block-sale2">
                                <img alt="hình" src="<?php echo URL;?>assets/frontend/assets/images/gift.png">
                            </div>
                            <?php }?>
                            <?php
                        } else {
                            ?>
                            <a href="<?php echo $url; ?>" title="title">
                                NOIMAGES
                            </a>
                            <?php
                        } //end if
                        ?>
                    </div>
                    <h3 class="col-md-7 title-top">
                        <a href="<?php echo $url; ?>" title="<?php echo $value['name_vi']; ?>">
                        	<?php if($pt > 0){?>
                        		<span class="box-sale-search">Giảm <?php echo $pt;?>%</span>
                        	<?php }?>
                        	<?php echo $value['name_vi']; ?>
                        </a>
                    </h3>
                    <div class="col-md-4 box-price nopadding">
                        <?php if($hienthi == 1){?>
                            <p class="price-top"><?php echo number_format($price, 0, "", "."); ?> đ</p>
                            <p class="price-sale-search"><?php echo number_format($value["price"], 0, "", "."); ?> đ</p>
                        <?php }else{?>
                        	<p class="price-top"><?php echo number_format($value["price"], 0, "", "."); ?> đ</p>
                        <?php }?>
                    </div>
                    
                </div>
                
    			
			<?php }?>
			
		</div>
		<!--list-pro-search-->
	</div>
	<?php }?>
	<?php if($t != 0){?>
		<a href="<?php echo URL?>search.jp?q=<?php echo $q;?>"
		class="seemore-top">Xem tất cả</a>
	<?php }else{?>
		<p style="color: #ff0000; font-family: &quot;Roboto&quot;,sans-serif; font-size: 16px; text-align: center; font-style: italic;padding: 5px;">Không tìm thấy từ khóa...</p>
	<?php }?>
</div>
<?php }?>