<link href="<?php echo URL_ASSET ?>frontend/assets/css/productFilter.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo URL_ASSET ?>frontend/assets/css/product3Column.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo URL_ASSET ?>frontend/assets/css/searchCustom.css" rel="stylesheet" type="text/css"/>
<?php
$this->headTitle("Tìm kiếm JAPANA");
$this->headMeta()
    ->setName('description', 'Siêu thị Nhật Bản chính hãng tại Japana.vn là nơi uy tín chuyên bán Mỹ phẩm Nhật, thảo dược Nhật Bản, đồ dùng gia đình... với mức giá tốt nhất. Gọi hotline: (028) 7108 8889 để được Siêu Thị Nhật Bản Japana tại TPHCM tư vấn miễn phí.')
    ->setProperty('og:title', "Tìm kiếm")
    ->setProperty('ROBOTS', "none");
?>
<?php
$this->header(array(
    "adapter" => $adapter,
    "active"  => $active
));
?>
<div class="site-inner">
    <div class="content-sidebar-wrap">
        <main class="search-list content">
            <form action="<?php echo $config["url"]; ?>" id="filter_from" method="get" name="form-data">
                <input value="<?php echo $_GET['q']; ?>" name="q" type="hidden">
                <div class="category-search">
                    <div class="container">
                        <?php if (isset($_GET['q'])) { ?>
                            <h2 class="text-search">
                                <i class="fa fa-search" aria-hidden="true"></i> Tìm kiếm từ khóa
                                <span>"<?= $_GET['q'] ?>"</span>
                            </h2>
                        <?php } ?>
                    </div>
                </div>
                <div class="category-search">
                    <?php if (isset($dataSearch['product']['data']) && !empty($dataSearch['product']['data'])) { ?>
                    <div class="container">
                        <aside class="sidebar sidebar-primary sidebar-filter left-side">
                            <?php if (!empty($count_category)): ?>
                                <section class="widget">
                                    <h3 class="title-box">Danh mục</h3>
                                    <div class="box-search">
                                        <input
                                                autocomplete="off"
                                                id='input_category_search'
                                                type="text"
                                                class="form-control input_search"
                                                placeholder="Tìm kiếm..."
                                                onkeyup="searchText('category_search')"
                                        >
                                        <button type="button">
                                            <i class="icon-mm icon-search-mm"></i>
                                        </button>
                                    </div>

                                    <div id="category_search" class="list-item">

                                        <div class="check-side check-all">


                                            <?php foreach ($count_category as $key => $value) : ?>

                                                <?php if (empty($value["id_parent1"])) { ?>

                                                    <?php if (isset($category_check_parent[$value['id']])) { ?>
                                                        <label class="check-custom"><?php echo $value["name_vi"]; ?>
                                                            <span class="count-item"> (<?php echo $value["count"]; ?>)</span>
                                                            <input name="category_parent[]" checked="checked"
                                                                   type="checkbox" value="<?php echo $value["id"]; ?>"
                                                                   class="selectall submit_click">
                                                            <span class="checkmark"></span>
                                                        </label>
                                                    <?php } else { ?>
                                                        <label class="check-custom"><?php echo $value["name_vi"]; ?>
                                                            <span class="count-item"> (<?php echo $value["count"]; ?>)</span>
                                                            <input name="category_parent[]" type="checkbox"
                                                                   value="<?php echo $value["id"]; ?>"
                                                                   class="selectall submit_click">
                                                            <span class="checkmark"></span>
                                                        </label>
                                                    <?php } ?>

                                                    <ul>
                                                        <?php foreach ($count_category as $key => $val) { ?>
                                                            <?php if ($value["id"] == $val["id_parent1"]) { ?>
                                                                <?php if (isset($category_check[$val['id']])) { ?>
                                                                    <li>
                                                                        <div class="check-side">
                                                                            <label class="check-custom"><?php echo $val["name_vi"] ?>
                                                                                <span class="count-item"> (<?php echo $val["count"] ?>)</span>
                                                                                <input checked="checked"
                                                                                       name="category[]"
                                                                                       class="child-cate submit_click"
                                                                                       value="<?php echo $val["id"]; ?>"
                                                                                       type="checkbox">
                                                                                <span class="checkmark"></span>
                                                                            </label>
                                                                        </div>
                                                                    </li>
                                                                <?php } else { ?>
                                                                    <li>
                                                                        <div class="check-side">
                                                                            <label class="check-custom"><?php echo $val["name_vi"] ?>
                                                                                <span class="count-item"> (<?php echo $val["count"] ?>)</span>
                                                                                <input name="category[]"
                                                                                       class="child-cate submit_click"
                                                                                       value="<?php echo $val["id"]; ?>"
                                                                                       type="checkbox">
                                                                                <span class="checkmark"></span>
                                                                            </label>
                                                                        </div>
                                                                    </li>
                                                                <?php } ?>
                                                            <?php } ?>
                                                        <?php } ?>
                                                    </ul>
                                                <?php } ?>

                                            <?php endforeach; ?>



                                        </div>

                                    </div>
                                </section>
                            <?php endif; ?>

                            <section class="widget">
                                <h3 class="title-box">GIÁ</h3>
                                <div id="slider-range"></div>
                                <input type="hidden" name="minprice" id="minprice" value="<?php echo $arrayParam["max_min"]["minPrice"];?>">
                                <input type="hidden" name="beginMinPrice" id="minprice1" value="<?php echo $arrayParam["beginMinPrice"];?>">
                                <input type="hidden" name="maxprice" id="maxprice" value="<?php echo $arrayParam["max_min"]["maxPrice"];?>">
                                <input type="hidden" name="endMaxPrice" id="maxprice1" value="<?php echo $arrayParam["endMaxPrice"];?>">
                                <div class="control">
                                    <div class="form-group">
                                        <p class="title-range">Min</p>
                                        <div class="box-input">
                                            <input autocomplete="off" type="text" class="slider_price_textbox price-all form-control" id="amount1" value='<?php echo $arrayParam['fromprice'];?>' disabled>
                                            <span>đ</span>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <p class="title-range">Max</p>
                                        <div class="box-input">
                                            <input autocomplete="off" type="text" class="slider_price_textbox price-all form-control" id="amount2" value='<?php echo $arrayParam['toprice'];?>' disabled>
                                            <span>đ</span>
                                        </div>
                                    </div>
                                </div>
                                <button class="submit_click btn-price" type="button">Áp dụng</button>
                            </section>

                            <?php if (!empty($count_brand)): ?>
                                <section class="widget">
                                    <h3 class="title-box">Thương hiệu</h3>
                                    <div class="box-search">
                                        <input
                                                autocomplete="off"
                                                id='input_brand_search'
                                                type="text"
                                                class="form-control input_search"
                                                placeholder="Tìm kiếm..."
                                                onkeyup="searchText('brand_search')"
                                        >
                                        <button type="button">
                                            <i class="icon-mm icon-search-mm"></i>
                                        </button>
                                    </div>

                                    <div id="brand_search" class="list-item">
                                        <?php foreach ($count_brand as $key => $value){?>
                                            <div class="check-side check-all" style="margin-bottom: 15px;">
                                                <label class="check-custom"><?php echo $value["name_vi"];?><span class="count-item"> (<?php echo $value["count"];?>)</span>
                                                    <?php if(isset($brand_check[$value['id']])){ ?>
                                                        <input checked="checked" name="id_brand[]" class="submit_click" type="checkbox" value="<?php echo $value["id"];?>" >
                                                        <span class="checkmark"></span>
                                                    <?php }else{?>
                                                        <input name="id_brand[]" class="submit_click" type="checkbox" value="<?php echo $value["id"];?>" >
                                                        <span class="checkmark"></span>
                                                    <?php }?>
                                                </label>
                                            </div>
                                        <?php }?>
                                    </div>
                                </section>
                            <?php endif; ?>


                        </aside>

                        <div class="box-cate card product-cate">
                            <h2 class="title-filter">
                                Sản phẩm
                            </h2>
                            <input name="order" id="order" value="<?php echo $arrayParam['order']?>" type="hidden">
                            <input name="sale" id="sale" value="<?php echo $arrayParam['sale'];?>" type="hidden">
                            <ul class="list-filter">
                                <li>Sắp xếp theo: </li>
                                <li><a href="javascript:order('');" title="Mặc định" class="<?php if(($arrayParam['order']=="" || $arrayParam['order'] == 'id asc') && $arrayParam['sale']=="") {?>active<?php }?> btn-circle-1">Mặc định</a></li>
                                <li><a href="javascript:order('price desc');" title="Giá cao" class="<?php if(($arrayParam['order'])=="price desc" && $arrayParam['sale']=="") {?>active<?php }?> btn-circle-1">Giá cao</a></li>
                                <li><a href="javascript:order('price asc');" title="Giá thấp" class="<?php if(($arrayParam['order'])=="price asc" && $arrayParam['sale']=="") {?>active<?php }?> btn-circle-1">Giá thấp</a></li>
                                <li><a href="javascript:order('name_vi asc');" title="A-z" class="<?php if(($arrayParam['order'])=="name_vi asc" && $arrayParam['sale']=="") {?>active<?php }?> btn-circle-1">A-z</a></li>
                                <li><a href="javascript:sale('2');" title="Sale" class="<?php if(($arrayParam['sale'])=="2") {?>active<?php }?> btn-circle-1">Sale</a></li>
                            </ul>
                                <div itemscope  itemtype="http://schema.org/Product" class="list-product">
                                    <?php $i = 0;
                                    foreach ($dataSearch['product']['data'] as $key => $value) {
                                        if ($arrayParam["offset"] <= $key && $i < $arrayParam["limit"]) {
                                        $i++;
                                        $price_promotion = "";
                                        $hienthi = 0;
                                        $text_qt = "";
                                        $images_qt = "";
                                        if ($value["status_product"] == 1 && strtotime($value["date_start"]) <= strtotime(date("y-m-d")) && strtotime($value["date_end"]) >= strtotime(date("y-m-d"))) {

                                            if (!empty($value["text_pt"])) {
                                                $price_promotion = $value["price"] - ($value["text_pt"] * $value["price"] / 100);
                                                $hienthi = 1;
                                            }
                                            if (!empty($value["text_vnd"])) {
                                                $hienthi = 1;
                                                $price_promotion = $value["price"] - $value["text_vnd"];
                                            }
                                        }
                                        $url_image = "";
                                        if (!empty($value['images'])) {
                                            $array = explode("-", $value['images']);
                                            $time = date("Y/m/d", $array[0]) . "/";
                                            $url_image = PATH_IMAGE_PRO . $time . "268x268-" . $value['images'];
                                        }
                                        $url = URL . $value["slug_vi"] . "-sp-" . $value["id"];
                                        $images = $url_image;
                                    ?>
                                            <div class="item item-product-custom">

                                                <?php if (!empty($value['images'])) : ?>

                                                    <div class="box-img">
                                                        <a href="<?php echo $url;?>" title="<?php echo $value["name_vi"];?>">
                                                            <img itemprop="image" src="<?php echo $images;?>" alt="<?php echo $value["name_vi"];?>">
                                                        </a>
                                                        <?php if( $value["status_product"] == 1 && strtotime($value["date_start"]) <= strtotime(date("y-m-d")) && strtotime($value["date_end"]) >= strtotime(date("y-m-d"))){ ?>

                                                            <?php if(!empty($value["text_pt"])){?>
                                                                <div class="block-sale">
                                                                    <img alt="<?php echo $value["text_pt"]?>" src="<?php echo $km_images;?>">
                                                                    <span class="sale">-<?php echo $value["text_pt"]?>%</span>
                                                                </div>
                                                            <?php }?>

                                                            <?php if(!empty($value["text_qt"])){?>
                                                                <div class="block-sale2">
                                                                    <img alt="<?php echo $km_images_qt;?>" src="<?php echo $km_images_qt;?>">
                                                                </div>
                                                                <?php
                                                                $text_qt = $value["text_qt"];
                                                                $images_qt = $km_images_qt;
                                                                ?>
                                                            <?php }?>

                                                        <?php }?>
                                                        <?php if($value["status_product_k"] == 1 && strtotime($value["date_start_k"]) <= strtotime(date("y-m-d")) && strtotime($value["date_end_k"]) >= strtotime(date("y-m-d"))){?>
                                                            <?php if(!empty($list_product[$value["id"]])){?>
                                                                <div class="block-sale3">
                                                                    <img alt="<?php echo $list_product[$value["id"]];?>" src="<?php echo $list_product[$value["id"]];?>">
                                                                </div>
                                                            <?php }?>
                                                        <?php }?>
                                                    </div>

                                                    <div class="detail">
                                                        <meta itemprop="mpn" content="<?php echo $value["sku"];?>" />
                                                        <meta itemprop="sku" content="<?php echo $value["sku"];?>" />
                                                        <div itemprop="description" style="display:none;"><?php echo $value["notes_vi"];?></div>
                                                        <h3 class="title">
                                                            <a itemprop="name" href="<?php echo $url;?>" title="<?php echo $value["name_vi"];?>"> <?php echo $this->cutString($value['name_vi'], 45); ?></a>
                                                        </h3>
                                                        <div itemprop="review" itemtype="http://schema.org/Review" itemscope>
                                                            <div itemprop="author" itemtype="http://schema.org/Person" itemscope>
                                                                <meta itemprop="name" content="Japana" />
                                                            </div>
                                                            <div itemprop="reviewRating" itemtype="http://schema.org/Rating" itemscope>
                                                                <meta itemprop="ratingValue" content="4" />
                                                                <meta itemprop="bestRating" content="5" />
                                                            </div>
                                                        </div>
                                                        <div itemprop="brand" itemtype="http://schema.org/Thing" itemscope>
                                                            <meta itemprop="name" content="<?php echo $value["brand"];?>" />
                                                        </div>
                                                        <ul itemprop="offers" itemtype="http://schema.org/Offer" itemscope class="box-price">
                                                            <meta itemprop="priceCurrency" content="VND" />
                                                            <link itemprop="url" href="https://japana.vn<?php echo $_SERVER["REQUEST_URI"];?>" />
                                                            <meta itemprop="availability" content="https://schema.org/InStock" />
                                                            <meta itemprop="priceValidUntil" content="2020-11-05" />
                                                            <?php if(intval($hienthi) > 0){ ?>
                                                                <li class="price">
                                                                    <span><?php echo number_format(intval($price_promotion), "0", ",", "."); ?> đ</span>
                                                                </li>
                                                                <li class="old-price">
                                                                    <span><?php echo number_format(intval($value['price']), 0, "", "."); ?> đ</span>
                                                                </li>
                                                            <?php }else{ ?>
                                                                <li class="price"><span><?php echo number_format(intval($value['price']), 0, "", "."); ?> đ</span></li>

                                                            <?php } ?>
                                                        </ul>
                                                    </div>

                                                <?php else: ?>

                                                    <a href="<?php echo $url; ?>" title="NOIMAGES">
                                                        NOIMAGES
                                                    </a>
                                                <?php endif; ?>

                                            </div>
                                       <?php } ?>
                                    <?php } ?>
                                </div>
                                <?php
                                if (isset($paginator)) {
                                    echo $this->paginationControl($paginator, 'Sliding', 'view/frontend/pagination', $params = array(
                                        'arrayParam' => $arrayParam
                                    ));
                                }
                                ?>
                        </div>
                    </div>
                </div>
                <?php } else { ?>
                    <p style="color: #ff0000; font-family: Roboto,sans-serif; font-size: 16px; text-align: center; font-style: italic;padding: 5px;">
                        Không tìm thấy từ khóa...</p>
                <?php } ?>
            </form>
        </main>
    </div>
</div>

<?php
$this->footer(array(
    "adapter" => $adapter
));
?>
<script>
    function order(id) {
        jQuery("#sale").val('');
        jQuery("#order").val(id);
        jQuery("#filter_from").submit()
    }
    function sale(id){
        jQuery("#order").val('');
    	jQuery("#sale").val(id);
    	jQuery("#filter_from").submit();
    }
</script>
<script>
    $('.list-item').each(function(){new PerfectScrollbar(this);});
    function limit(id) {
        jQuery("#limit").val(id);
        jQuery("#filter_from").submit()
    }
    jQuery(document).ready(function () {
        initCheckboxAll();
        initPressNumber();
        initSlidePrice();
    });
    var initCheckboxAll = function () {
        jQuery('.selectall').click(function () {
            if (jQuery(this).is(':checked')) {
                jQuery(this).parent().next().find('input[type=checkbox]').prop('checked', !0)
            } else {
                jQuery(this).parent().next().find('input[type=checkbox]').prop('checked', !1)
            }
        });
        $(".child-cate:input").click(function () {
            $parent = $(this).parent().parent().parent().parent().prev().find("input");
            if ($(this).parent().parent().parent().parent().find("input:checked").length == 0) {
                $parent.prop("checked", !1)
            } else {
                $parent.prop("checked", !0)
            }
        });
        jQuery('.clear-filter').click(function () {
            jQuery('.brand-filter input:checkbox').prop('checked', !1)
        });
        jQuery('.clear-filter2').click(function () {
            jQuery('.color-filter input:checkbox').prop('checked', !1)
        })
    };
    var initPressNumber = function () {
        jQuery('#amount1').change(function () {
            if (parseInt(formatCurrency2(jQuery('#amount1').val())) < parseInt(jQuery('#minprice').val())) {
                jQuery('#amount1').val(jQuery('#minprice').val())
            } else {
                jQuery('#minprice1').val(formatCurrency2(jQuery('#amount1').val()))
            }
            if (parseInt(formatCurrency2(jQuery('#amount1').val())) > parseInt(jQuery('#maxprice').val())) {
                jQuery('#amount1').val(jQuery('#minprice').val())
            } else {
                jQuery('#minprice1').val(formatCurrency2(jQuery('#amount1').val()))
            }
            if (parseInt(formatCurrency2(jQuery('#amount1').val())) > parseInt(formatCurrency2(jQuery('#amount2').val()))) {
                var min_number = formatCurrency2(jQuery('#amount2').val());
                jQuery('#amount2').val(jQuery('#amount1').val());
                jQuery('#maxprice1').val(formatCurrency2(jQuery('#amount1').val()));
                jQuery('#amount1').val(min_number);
                jQuery('#minprice1').val(min_number)
            }
        });
        jQuery('#amount2').change(function () {
            if (parseInt(formatCurrency2(jQuery('#amount2').val())) > parseInt(jQuery('#maxprice').val())) {
                jQuery('#amount2').val(jQuery('#maxprice').val())
            } else {
                jQuery('#maxprice1').val(formatCurrency2(jQuery('#amount2').val()))
            }
            if (parseInt(formatCurrency2(jQuery('#amount2').val())) < parseInt(jQuery('#minprice').val())) {
                jQuery('#amount2').val(jQuery('#maxprice').val())
            } else {
                jQuery('#maxprice1').val(formatCurrency2(jQuery('#amount2').val()))
            }
            if (parseInt(formatCurrency2(jQuery('#amount1').val())) > parseInt(formatCurrency2(jQuery('#amount2').val()))) {
                var min_number = jQuery('#amount2').val();
                jQuery('#amount2').val(jQuery('#amount1').val());
                jQuery('#maxprice1').val(formatCurrency2(jQuery('#amount1').val()));
                jQuery('#amount1').val(min_number);
                jQuery('#minprice1').val(formatCurrency2(min_number))
            }
        });

        function formatCurrency2(val) {
            return val.toString().replace(/\./g, "")
        }
    }

    function searchText(id) {
        var input, filter, li, a, i, txtValue;
        input = $('#input_'+id);
        filter = input.val().toUpperCase();
        li = $('#'+id+' .check-side');
        for (i = 0; i < li.length; i++) {
            a = li[i].getElementsByTagName("label")[0];
            txtValue = a.textContent || a.innerText;
            if (txtValue.toUpperCase().indexOf(filter) > -1) {
                li[i].style.display = "";
            } else {
                li[i].style.display = "none";
            }
        }
    }

    var initSlidePrice = function () {
        var min_price1 = parseInt(jQuery("#minprice").val());
        var max_price1 = parseInt(jQuery("#maxprice").val());
        if (($("#minprice1")).val()) {
            var min_price = parseInt(jQuery("#minprice1").val())
        } else {
            var min_price = parseInt(jQuery("#minprice").val())
        }
        if (($("#maxprice1")).val()) {
            var max_price = parseInt(jQuery("#maxprice1").val())
        } else {
            var max_price = parseInt(jQuery("#maxprice").val())
        }
        jQuery("#slider-range").slider({
            range: !0,
            min: min_price1,
            max: max_price1,
            values: [min_price, max_price],
            slide: function (event, ui) {
                jQuery("#amount").html("$" + ui.values[0] + " - $" + ui.values[1]);
                var amount1 = formatCurrency(ui.values[0]);
                var amount2 = formatCurrency(ui.values[1]);
                jQuery("#amount1").val(amount1);
                jQuery("#amount2").val(amount2);
                jQuery("#minprice1").val(ui.values[0]);
                jQuery("#maxprice1").val(ui.values[1])
            }
        });
        jQuery("#amount").html("$" + jQuery("#slider-range").slider("values", 0) + " - $" + jQuery("#slider-range").slider("values", 1));
        var from1st = formatCurrency(min_price);
        var to1st = formatCurrency(max_price);
        $("#amount1").val(from1st);
        $("#amount2").val(to1st);
        jQuery(".slider_price_textbox").on("keypress,keyup", function (e) {
            var code = e.charCode || e.keyCode;
            if (code == '8') return !0;
            if (String.fromCharCode(code).match(/[^0-9]/g)) {
                return !1
            }
            return !0
        });
        jQuery(".slider_price_textbox").focusout(function () {
            jQuery(this).val(formatCurrency(jQuery(this).val()))
        });
        jQuery(".slider_price_submit").click(function () {
            var from = formatNumber(jQuery("#amount1").val());
            var to = formatNumber(jQuery("#amount2").val());
            var sliderPriceURL = "http://japana.vn";
            sliderPriceURL = sliderPriceURL.replace("amshopby_slider_from", from);
            sliderPriceURL = sliderPriceURL.replace("amshopby_slider_to", to);
            jQuery(".slider_price_form").attr("action", sliderPriceURL);
            return !0
        });
        jQuery("#min-price").val(jQuery("#slider-range").slider("values", 0));
        jQuery("#max-price").val(jQuery("#slider-range").slider("values", 1));

        function formatCurrency(val) {
            return val.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ".")
        }

        function formatNumber(val) {
            return val.toString().split('.').join("")
        }

        function isNumberKey(evt) {
            var charCode = (evt.which) ? evt.which : event.keyCode;
            if (charCode == 59 || charCode == 46)
                return !0;
            if (charCode > 31 && (charCode < 48 || charCode > 57))
                return !1;
            return !0
        }
    }

    $(document).ready(function () {
        jQuery(".submit_click").click(function () {
            setTimeout(function () {
                jQuery("#filter_from").submit()
            }, 100)
        });
        var min_price1 = parseInt(jQuery("#minprice").val());
        var max_price1 = parseInt(jQuery("#maxprice").val());
        if (($("#minprice1")).val()) {
            var min_price = parseInt(jQuery("#minprice1").val())
        } else {
            var min_price = parseInt(jQuery("#minprice").val())
        }
        if (($("#maxprice1")).val()) {
            var max_price = parseInt(jQuery("#maxprice1").val())
        } else {
            var max_price = parseInt(jQuery("#maxprice").val())
        }
        jQuery("#slider-range").slider({
            range: !0,
            min: min_price1,
            max: max_price1,
            values: [min_price, max_price],
            slide: function (event, ui) {
                jQuery("#amount").html("$" + ui.values[0] + " - $" + ui.values[1]);
                var amount1 = formatCurrency(ui.values[0]);
                var amount2 = formatCurrency(ui.values[1]);
                jQuery("#amount1").val(amount1);
                jQuery("#amount2").val(amount2);
                jQuery("#minprice1").val(ui.values[0]);
                jQuery("#maxprice1").val(ui.values[1])
            }
        });

        jQuery("#amount").html("$" + jQuery("#slider-range").slider("values", 0) + " - $" + jQuery("#slider-range").slider("values", 1));
        var from1st = formatCurrency(min_price);
        var to1st = formatCurrency(max_price);
        $("#amount1").val(from1st);
        $("#amount2").val(to1st);
        jQuery(".slider_price_textbox").on("keypress", function (e) {
            var code = e.charCode || e.keyCode;
            if (code == '8') return !0;
            if (String.fromCharCode(code).match(/[^0-9]/g)) {
                return !1
            }
            return !0
        });
        jQuery(".slider_price_textbox").keyup(function (e) {
            var code = e.charCode || e.keyCode;
            if (code == '8') return !0;
            if (String.fromCharCode(code).match(/[^0-9]/g)) {
                return !1
            }
            return !0
        });
        jQuery(".slider_price_textbox").focusout(function () {
            jQuery(this).val(formatCurrency(jQuery(this).val()))
        });
        jQuery(".slider_price_submit").click(function () {
            var from = formatNumber(jQuery("#amount1").val());
            var to = formatNumber(jQuery("#amount2").val());
            var sliderPriceURL = "http://japana.vn";
            sliderPriceURL = sliderPriceURL.replace("amshopby_slider_from", from);
            sliderPriceURL = sliderPriceURL.replace("amshopby_slider_to", to);
            jQuery(".slider_price_form").attr("action", sliderPriceURL);
            return !0
        });
        jQuery("#min-price").val(jQuery("#slider-range").slider("values", 0));
        jQuery("#max-price").val(jQuery("#slider-range").slider("values", 1));

        function formatCurrency(val) {
            return val.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ".")
        }

        function formatNumber(val) {
            return val.toString().split('.').join("")
        }

        function isNumberKey(evt) {
            var charCode = (evt.which) ? evt.which : event.keyCode;
            if (charCode == 59 || charCode == 46)
                return !0;
            if (charCode > 31 && (charCode < 48 || charCode > 57))
                return !1;
            return !0
        }
    })
</script>
