<?php if(!empty($list)){?>
	<?php foreach ($list as $value){?>
		<?php 
		  if(!empty($value["images"])){
			  $array = explode("-", $value["images"]);
			  $time = date("Y/m/d",$array[0])."/";
			  $images = PATH_IMAGE_PRO.$time."268x268-".$value["images"];
		  }else{
			  $images = "";
		  }
		  $name = $this->cutString($value["name_vi"],50);
		  $url = URL.$value["slug_vi"]."-sp-".$value["id"];
		  $price = number_format($value["price"],"0",",",".");
		?>
		<div class="item">
			<div class="box-item">
				<div class="box-img">
					<a href="<?php echo $url;?>" title="<?php echo $name;?>">
						<img src="<?php echo $images;?>" alt="<?php echo $name;?>">
					</a>
					
				</div>

				<div class="detail">
					<h3 class="title">
						<a href="<?php echo $url;?>" title="<?php echo $name;?>"><?php echo $name;?></a>
					</h3>
					<div class="box-price">
						 <span class="price-sale"></span>
						<span class="price"><?php echo $price;?> đ</span>
					</div>
				</div>
			</div>
			<button onclick="addCart(
				'<?php echo $value["id"]?>',
				1,
				'<?php echo $images;?>',
				'<?php echo $value["name_vi"];?>',
				'<?php echo $value["price"];?>',
				'<?php echo $url;?>',
				'<?php echo $value["sku"];?>',
				'<?php echo $value["kg"];?>'
			)" type="submit" class="buy-now convert-background-color-15B02A">Mua ngay</button>
		</div>
	<?php }?>
<?php }?>