<?php
$this->headTitle (empty($config["meta_web_title"])?$config["name_vi"]:$config["meta_web_title"]);
$this->headMeta ()
    ->appendName ( 'keywords',      $config["meta_web_keyword"])
    ->appendName ( 'description',   $config["name_vi"]." là thương hiệu luôn được đánh giá cao và chiếm nhiều niềm tin của người tiêu dùng vì những giá trị mang lại tốt nhất. ".$config["name_vi"]." tại Siêu Thị Japana luôn đảm bảo 100% chính hãng, giá thành tốt nhất, đảm bảo người tiêu dùng có sự lựa chọn đúng đắn khi đến với Japana.")
    ->setProperty('og:image',       PATH_IMAGE_BRAND.$config['og_image'])
    ->setProperty('og:description', $config["name_vi"]." là thương hiệu luôn được đánh giá cao và chiếm nhiều niềm tin của người tiêu dùng vì những giá trị mang lại tốt nhất. ".$config["name_vi"]." tại Siêu Thị Japana luôn đảm bảo 100% chính hãng, giá thành tốt nhất, đảm bảo người tiêu dùng có sự lựa chọn đúng đắn khi đến với Japana.")
    ->setProperty('og:title',       $config["og_title"])
    ->setProperty('og:url',         $config["url"])
    ->setProperty("og:type", "website")
    ->setProperty("og:site_name", "https://japana.vn");
    $this->headLink(array('rel' => 'canonical', 'href' => $config["url"]));
?>
<style>
.box-detail-cate{border:1px solid #cbcbcb;padding:25px 29px;margin-top:60px;display:inline-block}.box-detail-cate h3{font-weight:700;font-family:roboto;color:#e62e6b}.box-detail-cate p{margin-bottom:15px;line-height:1.8;font-family:roboto;color:#666}.box-detail-cate img{margin:0 1.5% 1.5% 0;width:300px;height:168px}.mota_sanphamcon{display:inline-block}.mota_sanphamcon p{margin-bottom:5px}
</style>
<?php
    foreach ($list_block as $key => $value){
        if($key == 1){
            echo '<div class="site-inner">
        			<div class="content-sidebar-wrap">
        				<main class="product content">
                        <div class="navigation">
                            <div class="container">
                                <ul>
                                    <li><a href="'.URL.'" title="title">Trang chủ</a></li>
                                    <li> / '. $config["name_vi"].'</li>
                                </ul>
                            </div>
                        </div>
                  </div>';
        }
        if($value["begin"] == 1){?>
        <style>
        #filter_from{
            margin-top: 10px;
        }
        </style>
        <form id="filter_from" name="form-data" action="<?php echo $config["url"];?>" method="GET">
            <div class="container">
        <?php
            
        }
        $namecode = $value["name_code"];
        $this->$namecode(array(
            "adapter" => $adapter,
            "active" => $active,
            "id_block_page" => $value["id"],
            "id_brand"    => $config["id"],
            "count"   => $arrayParam["count"],
            "name_vi" => $arrayParam["name_vi"],
            "paginator"     => $paginator,
            "arrayParam"    => $arrayParam,
            "url"           => $arrayParam["config_url"]
        ));
        if($value["end"] == 1){?>
               <div class="clear"></div>
                </form>
			</div>
        <?php 
        }
        if($key == (count($list_block) - 2)){
            
            echo "</main></div></div>";
        }
    }
    
?>