<?php
if(!empty($info)) {
    $metaDesc = $info["meta_web_desc"];
    if(strlen($info["meta_web_desc"]) > 300){
        $metaDesc = substr($info["meta_web_desc"], 0 , 300);
    }
    $this->headTitle($info["meta_web_title"]);
    $this->headMeta()
        ->appendName('keywords', $info["meta_web_keyword"])
        ->appendName('description', $metaDesc)
        ->setProperty('fb:app_id',       "626517987552557")
        ->setProperty('og:url', $config["url"])
        ->setProperty("og:type", "article")
        ->setProperty('og:title', $info["og_title"])
        ->setProperty('og:locale',       "vi_VN")
        ->setProperty('og:site_name',       "japana.vn")
        ->setProperty('og:image', PATH_IMAGE_NEWS . $info["og_image"])
        ->setProperty('og:image:secure_url',PATH_IMAGE_NEWS . $info["og_image"])
        ->setProperty('og:image:width',       "600")
        ->setProperty('og:image:height',       "315")
        ->setProperty('og:description', $info["og_desc"]);
    $this->headLink(array('rel' => 'canonical', 'href' => $config["url"]));
} // end if
?>
<?php

$this->header(array(
    "adapter" => $adapter,
    "active" => $active));
?>
	<div class="site-inner">
        <div class="content-sidebar-wrap">
            <main class="news-detail content">

                <div class="navigation">
                    <div class="container">
                        <ul>
                            <li><a href="/" title="Trang chủ">Trang chủ</a></li>
                            <li> / Tin tức</li>
                        </ul>
                    </div>
                </div>

            	<div class="container">
                    <?php
                    foreach ($list_block as $key => $value) {
                        if ($key > 0) {
                            $namecode = $value["name_code"];
                            $this->$namecode(array(
                                "adapter" => $adapter,
                                "active" => $active,
                                "id" => $arrayParam["id"],
                                "url" => $config["url"],
                                "arrayParam" => $arrayParam,
                                "list" => $list,
                                "list_id_category" => $config["list_id_category"],
                            ));
                        }
                        if($key == (count($list_block) - 2)){
                            break;
                        }
                    }
                    ?>
			    </div>
        	</main>
        </div>
    </div>
<?php
$this->footer(array(
    "adapter" => $adapter));
?>
<style>
    .site-inner{
        background: #ffffff;
    }
</style>
<script>
	jQuery(document).ready(function(){
		loadProduct();
	});

	function loadProduct(){
    	var item = new Object();
    	item.name_code = 'product_item';
    	item.id = $(".id_sp").html();
    	$.ajax({
    		url: "<?php echo URL;?>frontend/ajaxs/index",
    		type: "POST",
    		data: item,
    		dataType: "html",
    		cache: false,
    		success: function(result)
    		{
    			$(".title_id_sp"+item.id).html(result);
    		}
    	});
    	timeout = setTimeout(function(){
            if(item.id > 0){
            	loadProduct();
    		}else{
    			clearTimeout(timeout);
    			return false;
    		}
        }, 300);
	}
</script>