<style>
    .custom-bg-news{
        background: white;
    }
    .item .box-img{
        margin-bottom: 0px !important;
    }
</style>
<?php
$this->headTitle ($info["meta_web_title"]);
$this->headMeta ()
    ->appendName ( 'keywords',      $info["meta_web_keyword"])
    ->appendName ( 'description',   $info["meta_web_desc"])
    ->setProperty('fb:app_id',       "626517987552557")
    ->setProperty('og:url',         $config["url"])
    ->setProperty("og:type", "article")
    ->setProperty('og:title',       $info["og_title"])
    ->setProperty('og:locale',       "vi_VN")
    ->setProperty('og:site_name',       "japana.vn")
    ->setProperty('og:image',       PATH_IMAGE_NEWS.$info["og_image"])
    ->setProperty('og:image:secure_url',PATH_IMAGE_NEWS . $info["og_image"])
    ->setProperty('og:image:width',       "600")
    ->setProperty('og:image:height',       "315")
    ->setProperty('og:description', $info["og_desc"]);
$this->headLink(array('rel' => 'canonical', 'href' => $config["url"]));
?>
<?php
$this->header(array(
    "adapter" => $adapter,
    "active" => $active));
?>
<div class="site-inner">
    <div class="content-sidebar-wrap">
        <main class="news-list content">
            <div class="navigation">
                <ul class="container">
                    <li><a href="<?php echo URL; ?>" title="Trang chủ">Trang chủ</a></li>
                    <li> / Tin tức</li>
                </ul>
            </div>
            <div class="custom-bg-news">
                <div class="container">

                    <?php
                    foreach ($list_block as $key => $value) {
                        if ($key > 0) {
                            $namecode = $value["name_code"];
                            $this->$namecode(array(
                                "adapter" => $adapter,
                                "active" => $active,
                                "id" => $arrayParam["id"],
                                "url" => $config["url"],
                                "arrayParam" => $arrayParam,
                                "list" => $list,
                                "list_id_category" => $config["list_id_category"],
                            ));
                        }
//                    if ($key == (count($list_block) - 2)) {
//                        break;
//                    }
                    }
                    ?>

                </div>
			</div>
        </main>
    </div>
</div>
<?php
$this->footer(array("adapter" => $adapter));
?>
<script>
    jQuery(document).ready(function() {
        
    });
    var product={
        phone_consulting:function (url,product,sku,linkurl,images) {
            var phone = $('#phone').val();
            if($.trim(phone) ==''){
                alert('Vui lòng nhập số điện thoại để được tư vấn !');
                return false;
            }
            if($.trim(phone).length < 10){
                alert('Số điện thoại không hợp lệ !');
                return false;
            }
            jQuery.ajax({
                type: "POST",
                url: url + 'phone-consulting.jp',
                cache: false,
                data: ({
                    phone:phone,
                    product:product,
                    sku:sku,
                    url:linkurl,
                    images:images
                }),
                beforeSend: function () {
                    //$("#showview"+id).html('...');
                },
                success: function (b) {
                    if(b == 'true') {
                        $('#phone').val('');
                        alert('Chúng tôi sẽ liên hệ với bạn nhanh nhất !');
                    }
                }
            });
        }
    }
</script>