<?php
    foreach ($best_seller as $key => $value) {

    $price_promotion = "";
    $hienthi = 0;
    $text_qt = "";
    $images_qt = "";
    if ($value["status_product"] == 1 && strtotime($value["date_start"]) <= strtotime(date("y-m-d")) && strtotime($value["date_end"]) >= strtotime(date("y-m-d"))) {
        if (!empty($value["text_pt"])) {
            $price_promotion = $value["price"] - ($value["text_pt"] * $value["price"] / 100);
            $hienthi = 1;
        }
        if (!empty($value["text_vnd"])) {
            $price_promotion = $value["price"] - $value["text_vnd"];
            $hienthi = 1;
        }
    }
    if (!empty($value["images"])) {
        $array = explode("-", $value["images"]);
        $time = date("Y/m/d", $array[0]) . "/";
        $images = PATH_IMAGE_PRO . $time . "268x268-" . $value["images"];
    } else {
        $images = "";
    }
    $name = $this->cutString($value["name_vi"], 40);
    $url = URL . $value["slug_vi"] . "-sp-" . $value["id"];
    $price = number_format($value["price"], "0", ",", ".");

    ?>
    <div class="item">
        <div class="box-img">
            <a href="<?php echo $url; ?>"
               title="<?php echo $name ?>">
                <img itemprop="image"
                     src="<?php echo $images; ?>"
                     alt="<?php echo $name ?>">
            </a>
            <?php if ($value["status_product"] == 1 && strtotime($value["date_start"]) <= strtotime(date("y-m-d")) && strtotime($value["date_end"]) >= strtotime(date("y-m-d"))) { ?>
                <?php if (!empty($value["text_pt"])) { ?>
                    <div class="block-sale">
                        <img alt="hình" src="<?php echo $km_images; ?>">
                        <span class="sale">-<?php echo $value["text_pt"] ?>%</span>
                    </div>
                <?php } ?>
                <?php if (!empty($value["text_qt"])) { ?>
                    <div class="block-sale2">
                        <img alt="hình" src="<?php echo $km_images_qt; ?>">
                    </div>
                    <?php
                    $text_qt = $value["text_qt"];
                    $images_qt = $km_images_qt;
                    ?>
                <?php } ?>
            <?php } ?>
            <?php if ($value["status_product_k"] == 1 && strtotime($value["date_start_k"]) <= strtotime(date("y-m-d")) && strtotime($value["date_end_k"]) >= strtotime(date("y-m-d"))) { ?>
                <?php if (!empty($list_product[$value["id"]])) { ?>
                    <div class="block-sale3">
                        <img alt="hình" src="<?php echo $list_product[$value["id"]]; ?>">
                    </div>
                <?php } ?>
            <?php } ?>
        </div>
        <div class="detail">
            <h3 class="title">
                <a href="<?php echo $url; ?>"
                   title="<?php echo $name ?>">
                    <?php echo $name ?>
                </a>
            </h3>
            <div class="other">
                <div class="price">
                    <?php if (intval($hienthi) > 0) { ?>
                        <span class="old-price"><?php echo $price; ?> đ</span>
                        <span class="new-price"><?php echo number_format($price_promotion, "0", ",", "."); ?>
                                        đ</span>
                    <?php } else { ?>
                        <span class="new-price"
                              style="width: 100%; text-align: right;"><?php echo $price; ?> đ</span>
                    <?php } ?>
                </div>
                <button onclick="addCart(
                    '<?php echo $value["id"] ?>',
                    1,
                    '<?php echo $images; ?>',
                    '<?php echo $value["name_vi"]; ?>',
                    '<?php
                if (intval($price_promotion) > 0) {
                    echo $price_promotion;
                } else {
                    echo $value["price"];
                }
                ?>',
                    '<?php echo $url; ?>',
                    '<?php echo $value["sku"]; ?>',
                    '<?php echo $value["kg"]; ?>'
                <?php if (!empty($text_qt)) {
                    echo ",'" . $text_qt . "'";
                } ?>
                <?php if (!empty($images_qt)) {
                    echo ",'" . $images_qt . "'";
                } ?>
                    )" type="button" class="btn-buy">
                    <i class="icon-m icon-buy"></i>
                </button>
            </div>
        </div>
    </div>
<?php } ?>