<div class="block-banner">
    <div class="banner2">
        <div class="hero-slider2">
        	<div class="box-1">
                <a rel="nofollow" href="#" title="title">
                	<img alt="slide" src="<?php echo URL_ASSET?>frontend/images/event3.png" class="img" >
                </a>
            </div>
        </div>
    </div>
    <div class="promo-banner">
        <div class="box-1">
            <a rel="nofollow" href="#" title="title">
                <img src="<?php echo URL_ASSET?>frontend/images/img-promo1.png" alt="title">
            </a>
        </div>
        <div class="box-2">
            <a rel="nofollow" href="#" title="title">
                <img src="<?php echo URL_ASSET?>frontend/images/img-promo2.png" alt="title">
            </a>
            <a rel="nofollow" href="#" title="title">
                <img src="<?php echo URL_ASSET?>frontend/images/img-promo3.png" alt="title">
            </a>
        </div>
    </div>
</div>
<div class="clear"></div>