<style>
    .banner-pro3 {
        margin-bottom: 20px;
        display: inline-block;
        width: 100%;
        float: left;
    }

    .banner-pro3 a {
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        width: 100%
    }

    .banner-pro3 a img {
        width: 100%
    }

    .banner-pro3 .box-big-img:hover {
        -webkit-box-shadow: 0 0 15px #333;
        box-shadow: 0 0 15px #333;
        -webkit-transition: .5s;
        -o-transition: .5s;
        transition: .5s;
        z-index: 2
    }

    .list-banner-pro3 {
        margin-top: 10px;
        background: #fff;
        height: 340px;
        display: none
    }

    .list-banner-pro3 .item {
        text-align: center;
        width: 20%;
        float: left;
        position: relative
    }

    .list-banner-pro3 .item .box-img,
    .list-banner-pro3 .item .box-img a {
        display: inline-block;
        position: relative;
        margin-top: 10px;
        margin-bottom: 0
    }

    .list-banner-pro3 .item .box-img a img {
        width: 80%;
        height: auto;
        margin: 15px auto;
        -webkit-transition: all ease .3s;
        -o-transition: all ease .3s;
        transition: all ease .3s
    }

    .list-banner-pro3 .item:hover .box-img a img {
        margin: 15px auto
    }

    .list-banner-pro3 .item .detail .title {
        margin-bottom: 0;
        height: 38px;
        overflow: hidden
    }

    .list-banner-pro3 .item .detail .price,
    .list-banner-pro3 .item .detail .title a {
        font-family: Roboto, sans-serif;
        font-weight: 400;
        font-size: 13px!important;
        color: #333;
        line-height: 1.5
    }

    .list-banner-pro3 .item .detail .title a:hover {
        color: #bb0029
    }

    .list-banner-pro3 .item .detail .price {
        color: #bb0029
    }

    .list-banner-pro3 .item .detail .old-price {
        color: #666;
        font-size: 14px;
        text-decoration: line-through;
        margin-left: 0
    }

    .list-banner-pro3 .item .detail .box-price {
        display: inline-block;
        line-height: 2;
        margin-top: 0
    }

    .list-banner-pro3 .item .detail {
        padding: 0 25px
    }

    .list-banner-pro3 .item .btn-mua3 {
        font-family: Roboto, sans-serif;
        font-weight: 400;
        font-size: 18px;
        color: #fff;
        background: #15b02a;
        border-radius: 2px;
        border: 0;
        display: none;
        position: absolute;
        bottom: 0;
        left: 50%;
        -webkit-transform: translate(-50%, 0);
        -ms-transform: translate(-50%, 0);
        transform: translate(-50%, 0);
        width: 150px;
        padding: 9px 0;
        border-radius: 4px;
        border: 1px solid #15b02a
    }

    .list-banner-pro3 .item:hover .btn-mua3 {
        display: block
    }

    .list-banner-pro3 .item .btn-mua3:hover {
        background: #fff;
        color: #15b02a
    }

    .list-banner-pro3 .item .box3item {
        display: inline-block;
        margin-top: 10px
    }

    .list-banner-pro3 .item .box3item:hover {
        margin-top: 10px;
        height: 340px;
        box-shadow: -2px 1px 7px -1px rgba(221, 228, 238, .75)
    }

    .list-banner-pro3 .block-sale,
    .list-banner-pro3 .block-sale2 {
        position: absolute;
        top: 0;
        right: 0
    }

    .list-banner-pro3 .block-sale {
        width: 100%;
        padding: 10px;
        padding-bottom: 0;
        text-align: right;
        padding-left: 0
    }

    .list-banner-pro3 .block-sale2 {
        bottom: 0;
        left: 0;
        top: auto;
        right: auto;
        padding: 10px;
        padding-right: 0;
        padding-top: 0;
        width: 100%;
        text-align: left
    }

    .list-banner-pro3 .block-sale3 {
        top: 0;
        left: 0;
        right: auto;
        text-align: left;
        position: absolute;
        padding-left: 10px;
        padding-top: 10px
    }

    .list-banner-pro3 .block-sale span {
        font-family: Roboto, sans-serif;
        font-size: 13px;
        font-weight: 500;
        color: #fff;
        position: absolute;
        top: 7px;
        right: 10px;
        width: 50px;
        height: 50px;
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
        -webkit-box-pack: center;
        -ms-flex-pack: center;
        justify-content: center
    }

    .list-banner-pro3 .block-sale {
        width: 60px;
        height: 60px
    }

    .list-banner-pro3 .block-sale3 {
        width: auto;
        max-height: 55px
    }

    .list-banner-pro3 .block-sale2 {
        width: 55px;
        height: 55px
    }

    .list-banner-pro3 .block-sale img,
    .list-banner-pro3 .block-sale2 img {
        height: auto;
        width: 100%
    }

    .list-banner-pro3 .block-sale3 img {
        max-height: 50px;
        width: auto
    }
</style>
<div class="banner-pro3">
	<div class="container">
        <?php 
       
            if(!empty($images["desktop"][0]["upload"][0])){
                $array = explode("-", $images["desktop"][0]["upload"][0]);
                $time = $array[0];
                $folder_date = PATH_IMAGE_BLOCK.date('Y',$time)."/".date('m',$time)."/".date('d',$time)."/".$images["desktop"][0]["upload"][0];
            }
        ?>
        <a href="<?php echo $images["desktop"][0]["link_images"][0];?>" class="box-big-img" title="<?php echo $images["desktop"][0]["name_images"][0];?>">
            <img src="<?php echo $folder_date;?>" alt="<?php echo $images["desktop"][0]["name_images"][0];?>">
        </a>
        <div class="list-banner-pro3 slide-custom">
            
            <?php
                if (!empty($sanphamgoiy)) {
            ?>
            <?php
                    foreach ($sanphamgoiy as $key => $value) {
                        $array = explode("-", $value["images"]);
                        $time = date("Y/m/d", $array[0]) . "/";
                        $images = PATH_IMAGE_PRO . $time ."268x268-". $value["images"];
                        $url = URL . $value["slug_vi"] . "-sp-" . $value["id"];
                        
                        $price_promotion = "";
                        $hienthi = 0;
                        $text_qt = "";
                        $images_qt = "";
                        if( $value["status_product"] == 1 && strtotime($value["date_start"]) <= strtotime(date("y-m-d")) && strtotime($value["date_end"]) >= strtotime(date("y-m-d"))){
                            if(!empty($value["text_pt"])){
                                $price_promotion = $value["price"] - ($value["text_pt"]*$value["price"]/100);
                                $hienthi = 1;
                            }
                            if(!empty($value["text_vnd"])){
                                $hienthi = 1;
                                $price_promotion = $value["price"] - $value["text_vnd"];
                            }
                        }
                        ?>
            <div class="item item-product-custom ">
                <div class="box3item">
                    <div class="box-img">
                         <a href="<?php echo $url; ?>" title="<?php echo $value["name_vi"]; ?>">
                            <img src="<?php echo $images;?>" alt="<?php echo $value["name_vi"]; ?>">
                         </a>
                        <?php
                            if( $value["status_product"] == 1 && strtotime($value["date_start"]) <= strtotime(date("y-m-d")) && strtotime($value["date_end"]) >= strtotime(date("y-m-d"))){?>
                                <?php if(!empty($value["text_pt"])){?>
                                    <div class="block-sale">
                                        <img alt="hình" src="<?php echo $km_images;?>">
                                        <span class="sale">-<?php echo $value["text_pt"]?>%</span>
                                    </div>
                                <?php }?>
                                <?php if(!empty($value["text_qt"])){?>
                                    <div class="block-sale2">
                                        <img alt="hình" src="<?php echo $km_images_qt;?>">
                                    </div>
                                    <?php 
                                        $text_qt = $value["text_qt"];
                                        $images_qt = $km_images_qt;
                                    ?>
                                <?php }?>
                            <?php }?>
                            <?php if($value["status_product_k"] == 1 && strtotime($value["date_start_k"]) <= strtotime(date("y-m-d")) && strtotime($value["date_end_k"]) >= strtotime(date("y-m-d"))){?>
                                <?php if(!empty($list_product[$value["id"]])){?>
                                    <div class="block-sale3">
                                        <img alt="hình" src="<?php echo $list_product[$value["id"]];?>">
                                    </div>
                                <?php }?>
                        <?php }?>
                </div>
                    <div class="detail">
                        <h3 class="title">
                            <a href="<?php echo $url; ?>" title="<?php echo $value["name_vi"]; ?>">
                                <?php echo $this->cutString($value["name_vi"],60); ?>
                            </a>
                        </h3>
                         <ul class="box-price">
                            <?php if (intval($hienthi) > 0) { ?>
                                <li class="price">
                                    <span><?php echo number_format(intval($price_promotion), "0", ",", "."); ?>đ</span>
                                </li>

                                <li class="old-price">
                                    <span><?php echo number_format($value["price"], 0, "", "."); ?> đ</span>
                                </li>
                            <?php } else { ?>
                                <li class="price" style="width: 100%;">
                                    <span><?php echo number_format($value["price"], 0, "", "."); ?> đ</span>
                                </li>
                            <?php } ?>
                        </ul>
                    </div>


            </div>
            </div>
                <?php }?>
            <?php }?>
        </div>
	</div>
</div>
<script>
    jQuery(document).ready(function () {
        initItemSliderPro();
    });
    var initItemSliderPro = function () {
        jQuery(".list-banner-pro3")
            .not(".slick-initialized")
            .slick({
                autoplay: !1,
                dots: !1,
                infinite: !0,
                centerMode: !1,
                speed: 300,
                slidesToShow: 5,
                slidesToScroll: 5,
                variableWidth: !1,
                autoplaySpeed: 2e3,
                nextArrow: '<span class="slick-next"><i class="ti ti-angle-right"></i></span>',
                prevArrow: '<span class="slick-prev"><i class="ti ti-angle-left"></i></span>',
                responsive: [
                    { breakpoint: 1024, settings: { slidesToShow: 5, slidesToScroll: 1, infinite: !0, dots: !1 } },
                    { breakpoint: 600, settings: { slidesToShow: 4, slidesToScroll: 1 } },
                    { breakpoint: 480, settings: { slidesToShow: 1, slidesToScroll: 1 } },
                ],
            });
    };

</script>