<link rel="stylesheet" href="http://test.jpe.vn/admins/plugins/select2/css/select2.min.css">


<link href="<?php echo URL_ASSET?>frontend/assets/css/checkoutCustom.css" rel="stylesheet" type="text/css" />

<!--START header-->
<?php
$this->header(array(
    "adapter" => $adapter,
    "active" => $active
));

?>
<!--END header-->

<div class="checkout">
    <div class="container">

        <div class="content-checkout">
            <div class="box-customer">
                <div class="card">
                    <div class="card-header">
                        <h3 class="title-cart m-0">
                            Thông tin giao hàng
                        </h3>
                    </div>
                    <div class="card-body">
                        <div class="info-checkout form-group">
                            <div class="item"><label for="representation" id="representation" class="label-change">Họ và tên</label> <input type="text" name="representation" id="representation" class="form-control" /></div>

                            <div class="item"><label for="phone" id="phone" class="label-change">Số điện thoại</label> <input type="text" name="phone" id="phone" class="form-control" /></div>
                            <div class="item">
                                <label for="province_code" id="province_code" class="label-change">Tỉnh/ Thành phố</label>
                                <select id="province_code" name="province_code" class="btn-location select2-hidden-accessible" tabindex="-1" aria-hidden="true" data-select2-id="province_code">
                                    <option value="0" data-select2-id="397">Chọn...</option>
                                    <option value="200008" data-select2-id="398">Tỉnh Tuyên Quang</option>
                                    <option value="200010" data-select2-id="399">Tỉnh Lào Cai</option>
                                    <option value="200011" data-select2-id="400">Tỉnh Điện Biên</option>
                                    <option value="200012" data-select2-id="401">Tỉnh Lai Châu</option>
                                    <option value="200014" data-select2-id="402">Tỉnh Sơn La</option>
                                    <option value="200015" data-select2-id="403">Tỉnh Yên Bái</option>
                                    <option value="200017" data-select2-id="404">Tỉnh Hoà Bình</option>
                                    <option value="200019" data-select2-id="405">Tỉnh Thái Nguyên</option>
                                    <option value="200020" data-select2-id="406">Tỉnh Lạng Sơn</option>
                                    <option value="200022" data-select2-id="407">Tỉnh Quảng Ninh</option>
                                    <option value="200024" data-select2-id="408">Tỉnh Bắc Giang</option>
                                    <option value="200025" data-select2-id="409">Tỉnh Phú Thọ</option>
                                    <option value="200026" data-select2-id="410">Tỉnh Vĩnh Phúc</option>
                                    <option value="200027" data-select2-id="411">Tỉnh Bắc Ninh</option>
                                    <option value="200030" data-select2-id="412">Tỉnh Hải Dương</option>
                                    <option value="200031" data-select2-id="413">Thành phố Hải Phòng</option>
                                    <option value="200033" data-select2-id="414">Tỉnh Hưng Yên</option>
                                    <option value="200034" data-select2-id="415">Tỉnh Thái Bình</option>
                                    <option value="200035" data-select2-id="416">Tỉnh Hà Nam</option>
                                    <option value="200036" data-select2-id="417">Tỉnh Nam Định</option>
                                    <option value="200037" data-select2-id="418">Tỉnh Ninh Bình</option>
                                    <option value="200038" data-select2-id="419">Tỉnh Thanh Hóa</option>
                                    <option value="200040" data-select2-id="420">Tỉnh Nghệ An</option>
                                    <option value="200042" data-select2-id="421">Tỉnh Hà Tĩnh</option>
                                    <option value="200044" data-select2-id="422">Tỉnh Quảng Bình</option>
                                    <option value="200045" data-select2-id="423">Tỉnh Quảng Trị</option>
                                    <option value="200046" data-select2-id="424">Tỉnh Thừa Thiên Huế</option>
                                    <option value="200048" data-select2-id="425">Thành phố Đà Nẵng</option>
                                    <option value="200049" data-select2-id="426">Tỉnh Quảng Nam</option>
                                    <option value="200051" data-select2-id="427">Tỉnh Quảng Ngãi</option>
                                    <option value="200052" data-select2-id="428">Tỉnh Bình Định</option>
                                    <option value="200054" data-select2-id="429">Tỉnh Phú Yên</option>
                                    <option value="200056" data-select2-id="430">Tỉnh Khánh Hòa</option>
                                    <option value="200058" data-select2-id="431">Tỉnh Ninh Thuận</option>
                                    <option value="200060" data-select2-id="432">Tỉnh Bình Thuận</option>
                                    <option value="200062" data-select2-id="433">Tỉnh Kon Tum</option>
                                    <option value="200064" data-select2-id="434">Tỉnh Gia Lai</option>
                                    <option value="200066" data-select2-id="435">Tỉnh Đắk Lắk</option>
                                    <option value="200067" data-select2-id="436">Tỉnh Đắk Nông</option>
                                    <option value="200068" data-select2-id="437">Tỉnh Lâm Đồng</option>
                                    <option value="200070" data-select2-id="438">Tỉnh Bình Phước</option>
                                    <option value="200072" data-select2-id="439">Tỉnh Tây Ninh</option>
                                    <option value="200074" data-select2-id="440">Tỉnh Bình Dương</option>
                                    <option value="200075" data-select2-id="441">Tỉnh Đồng Nai</option>
                                    <option value="200077" data-select2-id="442">Tỉnh Bà Rịa - Vũng Tàu</option>
                                    <option value="200079" data-select2-id="443">Thành phố Hồ Chí Minh</option>
                                    <option value="200080" data-select2-id="444">Tỉnh Long An</option>
                                    <option value="200082" data-select2-id="445">Tỉnh Tiền Giang</option>
                                    <option value="200083" data-select2-id="446">Tỉnh Bến Tre</option>
                                    <option value="200084" data-select2-id="447">Tỉnh Trà Vinh</option>
                                    <option value="200001" data-select2-id="448">Thành Phố Hà Nội</option>
                                    <option value="200086" data-select2-id="449">Tỉnh Vĩnh Long</option>
                                    <option value="200087" data-select2-id="450">Tỉnh Đồng Tháp</option>
                                    <option value="200089" data-select2-id="451">Tỉnh An Giang</option>
                                    <option value="200091" data-select2-id="452">Tỉnh Kiên Giang</option>
                                    <option value="200092" data-select2-id="453">Thành Phố Cần Thơ</option>
                                    <option value="200093" data-select2-id="454">Tỉnh Hậu Giang</option>
                                    <option value="200094" data-select2-id="455">Tỉnh Sóc Trăng</option>
                                    <option value="200095" data-select2-id="456">Tỉnh Bạc Liêu</option>
                                    <option value="200096" data-select2-id="457">Tỉnh Cà Mau</option>
                                    <option value="200002" data-select2-id="458">Tỉnh Hà Giang</option>
                                    <option value="200004" data-select2-id="459">Tỉnh Cao Bằng</option>
                                    <option value="200006" data-select2-id="460">Tỉnh Bắc Kạn</option>
                                </select>
                                <span class="select2 select2-container select2-container--default" dir="ltr" data-select2-id="332" style="width: 173px;">
                                    <span class="selection">
                                        <span class="select2-selection select2-selection--single btn-location" role="combobox" aria-haspopup="true" aria-expanded="false" tabindex="0" aria-disabled="false" aria-labelledby="select2-province_code-container">
                                            <span class="select2-selection__rendered" id="select2-province_code-container" role="textbox" aria-readonly="true" title="Tỉnh Tuyên Quang">Tỉnh Tuyên Quang</span>
                                            <span class="select2-selection__arrow" role="presentation"><b role="presentation"></b></span>
                                        </span>
                                    </span>
                                    <span class="dropdown-wrapper" aria-hidden="true"></span>
                                </span>
                            </div>
                            <div class="item">
                                <label for="district_code" id="district_code" class="label-change">Quận/ Huyện</label>
                                <select id="district_code" name="district_code" class="btn-location select2-hidden-accessible" tabindex="-1" aria-hidden="true" data-select2-id="district_code">
                                    <option value="0" data-select2-id="324">Chọn...</option>
                                    <option value="300070" data-select2-id="325">Thành phố Tuyên Quang</option>
                                    <option value="300071" data-select2-id="326">Huyện Lâm Bình</option>
                                    <option value="300072" data-select2-id="327">Huyện Nà Hang</option>
                                    <option value="300073" data-select2-id="328">Huyện Chiêm Hóa</option>
                                    <option value="300074" data-select2-id="329">Huyện Hàm Yên</option>
                                    <option value="300075" data-select2-id="330">Huyện Yên Sơn</option>
                                    <option value="300076" data-select2-id="331">Huyện Sơn Dương</option>
                                </select>
                                <span class="select2 select2-container select2-container--default" dir="ltr" data-select2-id="315" style="width: 180px;">
                                    <span class="selection">
                                        <span class="select2-selection select2-selection--single btn-location" role="combobox" aria-haspopup="true" aria-expanded="false" tabindex="0" aria-disabled="false" aria-labelledby="select2-district_code-container">
                                            <span class="select2-selection__rendered" id="select2-district_code-container" role="textbox" aria-readonly="true" title="Thành phố Tuyên Quang">Thành phố Tuyên Quang</span>
                                            <span class="select2-selection__arrow" role="presentation"><b role="presentation"></b></span>
                                        </span>
                                    </span>
                                    <span class="dropdown-wrapper" aria-hidden="true"></span>
                                </span>
                            </div>
                            <div class="item">
                                <label for="ward_code" id="ward_code" class="label-change">Phường/ Xã</label>
                                <select id="ward_code" name="ward_code" class="btn-location select2-hidden-accessible" tabindex="-1" aria-hidden="true" data-select2-id="ward_code">
                                    <option value="0" data-select2-id="301">Chọn...</option>
                                    <option value="402200" data-select2-id="302">Phường Phan Thiết</option>
                                    <option value="402203" data-select2-id="303">Phường Minh Xuân</option>
                                    <option value="402206" data-select2-id="304">Phường Tân Quang</option>
                                    <option value="402209" data-select2-id="305">Xã Tràng Đà</option>
                                    <option value="402212" data-select2-id="306">Phường Nông Tiến</option>
                                    <option value="402215" data-select2-id="307">Phường Ỷ La</option>
                                    <option value="402216" data-select2-id="308">Phường Tân Hà</option>
                                    <option value="402218" data-select2-id="309">Phường Hưng Thành</option>
                                    <option value="402503" data-select2-id="310">Xã An Khang</option>
                                    <option value="402512" data-select2-id="311">Xã An Tường</option>
                                    <option value="402515" data-select2-id="312">Xã Lưỡng Vượng</option>
                                    <option value="402521" data-select2-id="313">Xã Thái Long</option>
                                    <option value="402524" data-select2-id="314">Xã Đội Cấn</option>
                                </select>
                                <span class="select2 select2-container select2-container--default" dir="ltr" data-select2-id="286" style="width: 158px;">
                                    <span class="selection">
                                        <span class="select2-selection select2-selection--single btn-location" role="combobox" aria-haspopup="true" aria-expanded="false" tabindex="0" aria-disabled="false" aria-labelledby="select2-ward_code-container">
                                            <span class="select2-selection__rendered" id="select2-ward_code-container" role="textbox" aria-readonly="true" title="Phường Phan Thiết">Phường Phan Thiết</span>
                                            <span class="select2-selection__arrow" role="presentation"><b role="presentation"></b></span>
                                        </span>
                                    </span>
                                    <span class="dropdown-wrapper" aria-hidden="true"></span>
                                </span>
                            </div>

                            <div class="item">
                                <label for="address" id="address" class="label-change">Địa chỉ</label>
                                <input type="text" name="address" id="address" class="form-control" />
                            </div>

                            <div class="item">
                                <label for="representation"  class="label-change">Email</label>
                                <input type="text" name="email"  class="form-control" />
                            </div>

                            <div class="item">
                                <label for="representation" class="label-change">Ghi chú</label>
                                <input type="text" name="note"  class="form-control" />
                            </div>


                        </div>

                    </div>
                </div>

            </div>
            <div class="list-cart">
                <div class="card">
                    <div class="card-header">
                        <h3 class="title-cart m-0">ĐƠN HÀNG <span>(2 sản phẩm)</span></h3>
                    </div>
                    <div class="card-body">
                        <table class="table table-responsive">
                            <thead>
                            <tr>
                                <th>Sản phẩm</th>
                                <th>SL</th>
                                <th>Thành tiền</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>Viên uống Collagen Teinei Suppon Komachi 62 viên</td>
                                <td>1</td>
                                <td>1,190,000 đ</td>
                            </tr>
                            <tr>
                                <td>Quần jean bé trai</td>
                                <td>1</td>
                                <td>100,000 đ</td>
                            </tr>
                            </tbody>
                        </table>
                        <div class="list-price">
                            <p><span>Tạm tính:</span> <span>1,290,000 đ</span></p>
                            <!---->
                            <!---->
                            <hr />
                            <p class="m-0"><span>Tổng cộng:</span> <span class="total-order">1,290,000 đ</span></p>
                        </div>
                    </div>
                </div>
                <button type="button" class="continue-checkout">THANH TOÁN</button>
            </div>
            <!---->
        </div>
    </div>
</div>









<!--START footer-->
<?php
$this->footer(array("adapter" => $adapter));
?>
<!--END footer-->