<?php
    use Zend\Session\Container;
    $session = new Container("cart");
    $list = array();
    if (!empty($session->data_thank)) {
        $list = json_decode($session->data_thank, true);
        $idCart = $session->idCart;
        $vanchuyen = $session->vanchuyen;
    }
?>
<style>
    .thanks {
        display: inline-block;
        text-align: center;
        width: 100%;
        padding: 60px 0
    }

    .thanks p {
        padding: 0 0 30px;
        display: flex;
        align-items: center;
        justify-content: center;
        text-transform: uppercase;
        line-height: 1.5;
        color: #bb0029 !important;
    }

    .thanks p span {
        margin-top: 5px;
    }

    .thanks p, .btn-thanks a {
        font-size: 16px;
        font-family: 'Roboto', sans-serif;
        color: #333
    }

    .thanks p img {
        margin-right: 15px;
        width: 65px
    }

    .btn-thanks a {
        display: inline-block;
        padding: 14px 25px;
        background: #e3e3e3;
        border-radius: 6px;
        border: 1px solid #ccc
    }

    .btn-thanks a:last-child {
        margin-left: 30px
    }

    .btn-thanks a:hover {
        background: #15b02a;
        border: 1px solid #15b02a;
        color: #fff
    }

    .box-note {
        display: inline-block;
        width: 71%;
        background: url(assets/images/Desktop.png) no-repeat center center;
        background-size: 100% 100%;
        font-size: 15px;
        font-family: 'Roboto', sans-serif;
        font-weight: 400;
        line-height: 1.5;
        padding: 21px 15px 12px;
        text-align: left;
        margin-bottom: 50px
    }

    .box-note span {
        color: #bb0029;
        font-weight: 500
    }
</style>
<?php
$this->headTitle("Japana Việt Nam");
$this->headMeta()
    ->appendName('keywords', "Japana Việt Nam")
    ->appendName('description', "Japana Việt Nam")
    ->setProperty('og:title', 'Japana Việt Nam');
?>
<?php $this->header(array(
    "adapter" => $adapter,
    "active"  => $active
)); ?>
<?php
if (!empty($session->data_thank)) {
    $list = json_decode($session->data_thank, true);
    $idCart = $session->idCart;
    $vanchuyen = $session->vanchuyen;
}

$tong = 0;
foreach ($list as $value3) {
    $tong = $tong + $value3["price_market"] * $value3["sl"];
    $tong2 = $tong2 + 10000 * $value3["sl"];
}
?>
<div class="site-inner">
    <div class="content-sidebar-wrap">
        <main class="thanks-end content">

            <div class="order-success">
                <p id="title-order-success">
                    Đặt hàng thành công! Cảm ơn bạn!
                </p>
                
                <p style="color: #0F83FF;
            padding: 20px;
            font-size: 15px;" class="order-alert">
                                ** Việc giao hàng có thể bị trì hoãn ở một số khu vực bị phong tỏa theo quy định của nhà nước. Mong quý khách thông cảm.
        Mọi thắc mắc vui lòng liên hệ CSKH <a style="display: contents; color: red" href="tel:02871088889">(028) 7108 8889</a>. Chân thành cám ơn.
                                </p>
            </div>
            
            <div class="container">
                <div class="thanks">
                    <!--            <a href="-->
                    <?php //echo URL;?><!--cung-japana-vn-mang-lai-anh-sang-cho-nguoi-ngheo-news-405.jp">-->
                    <!--				<p><img src="assets/images/icon-cart3.png" alt="title"> <span>Chúng tôi biết bạn có nhiều sự lựa chọn nhưng bạn đã chọn chúng tôi. <br>Xin cảm ơn!</p>-->
                    <!--				<div class="box-note">-->
                    <!--				  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Mỗi đơn hàng thành công, quý khách cùng Japana ủng hộ <span>10.000đ</span> vào quỹ <span>"Mổ mắt miễn phí cho người nghèo"</span> tại huyện Quế Sơn, tỉnh Quảng Nam. Chân thành cám ơn quý khách.-->
                    <!--				</div>-->
                    <!--			</a>-->

                    <div class="btn-thanks">
                        <a href="<?php echo URL; ?>theo-doi-don-hang.jp?code=<?php echo $post_code; ?>" title="Theo dõi đơn hàng" class="follow-order-button">Theo dõi đơn hàng</a>
                        <a href="<?php echo URL; ?>" title="Tiếp tục mua sắm" class="continue-buy-button">Tiếp tục mua sắm</a>
                    </div>
                </div>
                <?php
                $this->slider_product_sale_top(array("adapter" => $adapter));
                ?>
            </div>
        </main>
    </div>
</div>

<?php
$this->footer(array("adapter" => $adapter));
?>

<?php
if(!empty($session->data_thank)){
    
?>
<script>
    ga('require', 'ecommerce');
              ga('ecommerce:addItem', 

	  <?php
	         $i = 0;
	         $count = count($list);
	         foreach ($list as $trans) {?>
                 {
                      'id': '<?php echo $trans['id'];?>',
                      'name': '<?php echo $trans['name'];?>',
                      'sku': '<?php echo $trans['sku'];?>',
                      'price': '<?php echo $trans['price_market'];?>',
                      'quantity': '<?php echo $trans['sl'];?>'
                  }
                  <?php if(($i + 1) < $count ){
                      echo ",";
                  } $i++;?>
              ); ga('ecommerce:send');

				<?php }?>
</script>
<?php }?>




<!-- BEGIN GCR Language Code -->
<script>
  window.___gcfg = {
    lang: 'vi'
  };
</script>
<!-- END GCR Language Code -->
<!-- BEGIN GCR Opt-in Module Code -->
<script src="https://apis.google.com/js/platform.js?onload=renderOptIn" async defer></script>
<script>
  window.renderOptIn = function() {
    window.gapi.load('surveyoptin', function() {
      window.gapi.surveyoptin.render(
      {
        "merchant_id": 139845714,
        "order_id": "<?php echo $idCart;?>",
        "email": "<?php echo $_COOKIE[email]; ?>",
        "delivery_country": "VN",
        "estimated_delivery_date": "<?php echo date('Y-m-d'); ?>",

        // OPTIONAL
        "opt_in_style": "CENTER_DIALOG",
		"products": [
			<?php foreach ($list as $key => $value3){?>
			     <?php if($key == 0){?>
            	{"gtin":"<?php echo $value3["gtin"]?>"}
				<?php }?>
				<?php if($key > 0){?>
            		,{"gtin":"<?php echo $value3["gtin"]?>"}
				<?php }?>				
			<?php }?>
         ]

        
      });
    });
  }
</script>
<script>
  fbq('track', 'Purchase', {
    content_type: 'product',
    value: <?php echo $tong; ?>,
    currency: 'VND',
    content_ids: '<?php foreach ($list as $value3){
        echo $value3['sku'].",";
    } ?>',
  });
</script>
<?php if (!empty($session->data_thank)) { ?>
    <script type="text/javascript" src="//static.criteo.net/js/ld/ld.js" async="true"></script>
	<script type="text/javascript">
	  window.criteo_q = window.criteo_q || [];
	  window.criteo_q.push(
		{ event: "setAccount", account: 72566 },
		{ event: "setEmail", email: "marketing@japana.vn" },
		{ event: "setSiteType", type: "d" },
		{ event: "trackTransaction", id: "<?php echo $idCart;?>", item: [
		  <?php foreach ($list as $value3){ ?>
				{ id: "<?php echo $value3["id"] ?>", price: <?php echo $value3["price_market"] ?>, quantity: <?php echo $value3["sl"] ?> },
				<?php } ?>
		]}
	  );
    </script>
    <script>
        dataLayer.push({
        'ecommerce': {
            'purchase': {
            'actionField': {
                'id': '<?php echo $idCart;?>',                        
                'affiliation': 'Siêu thị nhật bản Japana',
                'revenue': '<?php echo $tong;?>',                 
                'tax':'0',
                'shipping': '<?php echo $vanchuyen;?>',
                'coupon': 'SUMMER_SALE'
            },
            'products': [<?php $count = count($list);
            $i = 0;
            foreach ($list as $key => $value){?>{                           
                'name': '<?php echo $value["name"]?>',
                'id': '<?php echo $value["id"]?>',
                'price': '<?php echo $value["price_market"];?>',
                'brand': '<?php echo $session->list_id_product[$value["id"]]["brand"]?>',
                'category': '<?php echo $session->list_id_product[$value["id"]]["category"]?>',
                'variant': 'Gray',
                'quantity': <?php echo $value["sl"];?>,
                'coupon': ''
            }<?php if(($i + 1) < $count ){
                echo ",";
            } $i++; }?>]
            }
        }
        });
    </script>
<?php
} ?>
