<?php
/*
    $fb = new Facebook([
            'app_id' => '626517987552557',
            'app_secret' => '487003c90a4c6cf5c81c07a08e064cd5',
            'default_graph_version' => 'v2.11',
        ]);
    $helper = $fb->getRedirectLoginHelper();
    $permissions = ['public_profile'];
    $loginUrl = $helper->getLoginUrl('http://dev.japana.vn/frontend/user/loginfb', $permissions);

    //echo $loginUrl;
*/
    $loginUrl = "https://www.facebook.com/v2.11/dialog/oauth?client_id=".APP_ID."&state=".APP_SECRET."&response_type=code&sdk=php-sdk-5.6.1&redirect_uri=http%3A%2F%2Fdev.japana.vn%2Ffrontend%2Fuser%2Floginfb&scope=public_profile";
?>
<!-- Register -->
<div class="custom_modal modal fade" id="Register" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-body">
				<ul class="nav nav-tabs">
				    <li class="active"><a class="title-log" data-toggle="tab" href="#register">Đăng ký</a></li>
				    <li><a class="title-log" data-toggle="tab" href="#login">Đăng nhập</a></li>
				</ul>
				<div class="tab-content">
				    <div id="register" class="tab-pane fade in active">
							<div class="box-input form-group">
								<div class="icon-form">
									<i class="fa fa-user" aria-hidden="true"></i>
								</div>
								<input id="name" type="text" name="name" placeholder="Họ và tên" class="form-control ipt-text">
							</div>

							<div class="box-input form-group">
								<div class="icon-form">
									<i class="fa fa-envelope" aria-hidden="true"></i>
								</div>
								<input id="email" type="email" name="email" placeholder="Email" class="form-control ipt-text">
							</div>
							<div class="box-input form-group">
								<div class="icon-form">
									<i class="fa fa-phone" aria-hidden="true"></i>
								</div>
								<input id="mobile" type="tel" name="mobile" placeholder="Số điện thoại" class="form-control ipt-text">
							</div>

							<div class="box-input form-group">
								<div class="icon-form">
									<i class="fa fa-lock" aria-hidden="true"></i>
								</div>
								<input id="password" type="password" name="password" placeholder="Mật khẩu" class="form-control ipt-text">
							</div>
							<div class="box-input form-group">
								<div class="icon-form">
									<i class="fa fa-lock" aria-hidden="true"></i>
								</div>
								<input id="re_password" type="password" name="re-password" placeholder="Xác nhận mật khẩu" class="form-control ipt-text">
							</div>
							
							<p style="display: none" id="warning-register" class="warning"><i class="fa fa-exclamation-triangle" aria-hidden="true"></i> Số điện thoại hoặc email đã tồn tại</p>
							<div class="box-check">
								<label class="check-custom">Bạn đã đọc và đồng ý với điều khoản sử dụng, mua bán và bảo mật của <a href="https://japana.vn/chinh-sach-bao-mat-static-7.jp" title="japana">Japana.vn</a>
								  <input type="checkbox" id="check-rule" checked="checked">
								  <span class="checkmark"></span>
								</label>
							</div>
							<div class="box-check2">
								<label class="check-custom">Đăng ký nhận khuyến mãi từ chúng tôi
								  <input type="checkbox" id="check-promo" checked="checked">
								  <span class="checkmark"></span>
								</label>
							</div>
							<button onclick="register_frontend();" type="button" name="regis-btn" class="btn-red">Tạo tài khoản</button>
							<input value="<?php echo "http://".$_SERVER["SERVER_NAME"].$_SERVER["REQUEST_URI"];?>" type="hidden" name="url">
					    
				    </div>
				    <div id="login" class="tab-pane fade">
				        
							<div class="box-input form-group">
								<div class="icon-form">
									<i class="fa fa-user" aria-hidden="true"></i>
								</div>
								<input id="username-login" type="text" name="username" placeholder="Email hoặc số điện thoại" class="form-control ipt-text">
							</div>
							<div class="box-input form-group">
								<div class="icon-form">
									<i class="fa fa-lock" aria-hidden="true"></i>
								</div>
								<input id="password-login" type="password" name="password" placeholder="Mật khẩu" class="form-control ipt-text">
							</div>
							
							<button onclick="login()" type="button" class="btn-red">Đăng nhập</button>
							<p style="margin-top: 10px;color: red;" id="error-login"></p>
							<div class="box-check login-popup">
								<label class="check-custom">Ghi nhớ tài khoản <a href="#" title="Quên mật khẩu?" data-toggle="modal" data-target="#ForgotPW" data-dismiss="modal" class="forgot-pass">Quên mật khẩu?</a>
								  <input type="checkbox" checked="checked">
								  <span class="checkmark"></span>
								</label>
							</div>
							<input value="<?php echo "http://".$_SERVER["SERVER_NAME"].$_SERVER["REQUEST_URI"];?>" type="hidden" name="url">
					    
				    </div>
				</div>
				
			</div>
		</div>
	</div>
</div>

<!-- Forgot Password -->
<div class="custom_modal modal fade" id="ForgotPW" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-body">
				<div class="box-modal">
					<p class="title-log">Lấy lại mật khẩu</p>
					<form method="GET">
						<p class="intro-log">
							Vui lòng nhập địa chỉ email của bạn vào ô bên dưới. Bạn sẽ nhận được một liên kết để thiết lập lại mật khẩu.
						</p>
						<div class="box-input form-group">
							<div class="icon-form">
								<i class="fa fa-envelope" aria-hidden="true"></i>
							</div>
							<input type="email" name="email" id="email_loss" placeholder="Nhập email của bạn" class="form-control ipt-text">
						</div>
						
						<button onclick="funcuser.losspass('<?php echo URL; ?>');" type="button" class="btn-red btn-loss-pass">Lấy lại mật khẩu</button>
						<a href="#Login" title="Quay lại trang đăng nhập" data-toggle="modal" data-target="#Register" data-dismiss="modal" class="link-return"><i class="fa fa-angle-double-left" aria-hidden="true"></i> Quay lại trang đăng nhập</a>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- Forgot Password -->
<div class="custom_modal modal fade" id="ForgotPW2" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-body">
				<div class="box-modal">
					<p class="title-log">Lấy lại mật khẩu</p>
					<form method="GET">
						<p class="intro-log">
							<i class="fa fa-check" aria-hidden="true"></i> Một địa chỉ email đã được gửi về mail của bạn, vui lòng check mail để tiến hành thay đổi mật khẩu.
						</p>
						<button type="submit" class="btn-red btn-loss-pass">OK</button>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

<script>
    var funcuser={
        losspass:function (url) {
            var filter = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
            var email = $('#email_loss').val();
            if ($.trim(email) == '') {
                $("#email_loss").css("border", "2px solid red");
                $("#email_loss").attr('placeholder', 'Bạn chưa nhập email');
                return false;
            }else{
                $("#email").css("border", "1px solid #ccc");
            }

            if (!filter.test(email)) {
                $("#email_loss").css("border", "2px solid red");
                alert('Email không hợp lệ');
                return false;
            }else{
            	// jQuery('.btn-loss-pass').prop('disable',true);
            	// jQuery('.btn-loss-pass').css('background','#ccc');
                $("#email_loss").css("border", "1px solid #ccc");
            }
            jQuery.ajax({
                type: "POST",
                url: url + 'frontend/user/losspassword',
                cache: false,
                data: ({
                    email:email
                }),
                beforeSend: function () {
                    //$("#showview"+id).html('...');
                },
                success: function (b) {
                    if(b == 'true'){
                        $('#ForgotPW2').show();
                        $('#ForgotPW2').addClass('in');
                        $('#ForgotPW').hide();
                        $('#ForgotPW').removeClass('in');
                    }else{
                    	jQuery('.btn-loss-pass').prop('disable',false);
                        alert('Địa chỉ email không tồn tại trên hệ thống của JAPANA.')
                    }
                }
            });
        }
    }
</script>