<div class="banner">
    <div class="hero-slider">
        <div class="item" data-title="1 tặng 1">
            <img alt="slide" src="<?php echo URL_ASSET?>frontend/images/banner.png" class="img" >
        </div>
        <div class="item" data-title="Giảm giá tận gốc">
            <img alt="slide" src="<?php echo URL_ASSET?>frontend/images/banner1.png" class="img" >
        </div>
        <div class="item" data-title="Giảm 50% tất cả sản phẩm">
            <img alt="slide" src="<?php echo URL_ASSET?>frontend/images/banner2.png" class="img" >
        </div>
        <div class="item" data-title="Giao hàng nhanh">
            <img alt="slide" src="<?php echo URL_ASSET?>frontend/images/banner3.png" class="img" >
        </div>
    </div>
</div>