<link href="<?php echo URL_ASSET?>frontend/assets/css/productFullWidth.css" rel="stylesheet" type="text/css" />
<?php if(!empty($list)){?>
<div class="bottom-pro">
    <div class="container">
        <div class="block-pro">
            <?php
                if(!empty($images_banner["desktop"][0]["upload"][0])){
                $array = explode("-", $images_banner["desktop"][0]["upload"][0]);
                $time = $array[0];
                $folder_date = PATH_IMAGE_BLOCK.date('Y',$time)."/".date('m',$time)."/".date('d',$time)."/".$images_banner["desktop"][0]["upload"][0];
            ?>
        	<div class="banner-pro-full">
                <a href="<?php echo $images_banner["desktop"][0]["link_images"][0];?>" title="<?php echo $images_banner["desktop"][0]["name_images"][0];?>">
                    <img src="<?php echo $folder_date;?>" alt="<?php echo $images_banner["desktop"][0]["name_images"][0];?>">
                </a>
            </div>
            <?php } ?>
        	<div class="list-pro-bottom">
        	<?php foreach ($list as $value){?>
        		<?php
        		  $array = explode("-", $value["images"]);
        		  $time = date("Y/m/d",$array[0])."/";
        		  $images = PATH_IMAGE_PRO.$time."268x268-".$value["images"];
        		  $name = $value["name_vi"];
        		  $url = URL.$value["slug_vi"]."-sp-" . $value["id"];
        		  $price = number_format($value["price"],"0",",",".");

        		  $price_promotion = "";
        		  $hienthi = 0;
        		  $text_qt = "";
        		  $images_qt = "";
        		  if( $value["status_product"] == 1 && strtotime($value["date_start"]) <= strtotime(date("y-m-d")) && strtotime($value["date_end"]) >= strtotime(date("y-m-d"))){
            		  if(!empty($value["text_pt"])){
            		      $price_promotion = $value["price"] - ($value["text_pt"]*$value["price"]/100);
            		      $hienthi = 1;
            		  }
            		  if(!empty($value["text_vnd"])){
            		      $price_promotion = $value["price"] - $value["text_vnd"];
            		      $hienthi = 1;
            		  }
        		  }
        		?>
        		<div class="item item-product-custom">
                    <div class="box-item">
                        <div class="box-img">
                            <a href="<?php echo $url;?>" title="<?php echo $name;?>">
                                <img src="<?php echo $images;?>" alt="<?php echo $name;?>">
                            </a>
                            <?php
                            if( $value["status_product"] == 1 && strtotime($value["date_start"]) <= strtotime(date("y-m-d")) && strtotime($value["date_end"]) >= strtotime(date("y-m-d"))){?>
                                <?php if(!empty($value["text_pt"])){?>
                                    <div class="block-sale">
                                       <img src="<?php echo $km_images;?>" alt="hình">
                                        <span class="sale">-<?php echo $value["text_pt"]?>%</span>
                                    </div>
                                <?php }?>
                                <?php if(!empty($value["text_qt"])){?>
                                    <div class="block-sale2">
                                            <img src="<?php echo $km_images_qt;?>" alt="hình">
                                    </div>
                                    <?php
                                        $text_qt = $value["text_qt"];
                                        $images_qt = $km_images_qt;
                                    ?>
                                <?php }?>
                            <?php }?>
                            <?php if($value["status_product_k"] == 1 && strtotime($value["date_start_k"]) <= strtotime(date("y-m-d")) && strtotime($value["date_end_k"]) >= strtotime(date("y-m-d"))){?>
                                <?php if(!empty($list_product[$value["id"]])){?>
                                    <div class="block-sale3">
                                        
                                            <img src="<?php echo $list_product[$value["id"]];?>" alt="hình">
                                        
                                    </div>
                                <?php }?>
                            <?php }?>
                        </div>
                        <div class="detail">
                            <p class="title">
                                <a href="<?php echo $url;?>" title="<?php echo $name;?>"><?php echo $this->cutString($name,60);?></a>
                            </p>
                            <div class="box-price">
                                <?php if(intval($hienthi) > 0){ ?>
                                <p class="price"><?php echo number_format($price_promotion,"0",",",".");?> đ</p>
                                <p class="old-price"><?php echo $price;?> đ</p>
                                <?php }else{ ?>
                                <p class="price"><?php echo $price;?> đ</p>
                                <?php } ?>
                            </div>
                        </div>
                    </div>
        		</div>
        	<?php }?>
        	</div>
        </div>

        <?php
            if(isset($paginator)){
    		     echo $this->paginationControl($paginator, 'Sliding', 'view/frontend/pagination', $params = array('arrayParam' => $arrayParam));
            }
    	?>

    </div>
</div>
<?php }?>