<style>
    .block-5-img .item,
    .block-5-img .item a {
        width: 285px;
        margin-right: 10px;
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        float: left
    }

    .block-5-img .item a {
        margin-right: 0;
        width: 100%
    }

    .block-5-img .item a:hover {
        -webkit-box-shadow: 0 0 15px #333;
        box-shadow: 0 0 15px #333;
        -webkit-transition: 0.5s;
        -o-transition: 0.5s;
        transition: 0.5s;
        z-index: 2
    }

    .block-5-img .item:first-child {
        margin-top: 0;
        width: 100%;
        margin-right: 0;
        margin-bottom: 0px
    }

    .block-5-img .item:last-child {
        margin-right: 0
    }

    .block-5-img {
        margin-top: 0px;
        margin-bottom: 20px;
        display: inline-block;
        width: 100%;
    }

    .img{
        width: 285px;
        height: auto;
    }

    .img:first-child{
        width: 100%;
        height: auto;
    }


</style>
<div class="block-5-img">
	<div class="container">
		<?php foreach ($images["desktop"] as $key => $value){
	        if(!empty($value["upload"][0])){
	        $array = explode("-", $value["upload"][0]);
	        $time = $array[0];
	        $folder_date = PATH_IMAGE_BLOCK.date('Y',$time)."/".date('m',$time)."/".date('d',$time)."/".$value["upload"][0];
	    ?>
	    <div class="item">
	    	<a href="<?php echo $value["link_images"][0];?>" title="<?php echo $value["name_images"][0];?>">
	    		<img src="<?php echo $folder_date;?>" class="img" alt="<?php echo $value["name_images"][0];?>">
	    	</a>
	    </div>
	    <?php }}?>
	</div>
</div>