<!--->
<div class="item_bl_group">
    <div class="item_top_comment">
        <div class="left_avatar">
                        <span class="avatar_user"
                              style="background-image: url('https://i.pinimg.com/564x/92/26/5c/92265c40c8e428122e0b32adc1994594.jpg');"></span>
        </div>
        <div class="right_comment">
            <p class="fullname_bl">Carly West</p>
            <p>
                        <span class="rating_bl">
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                        </span>
                <span class="date_bl">
                            (22/08/2021)
                        </span>
            </p>
        </div>
    </div>

    <div class="content_comment">
        <p class="dotdot_content dotdotdot">
            I am very happy to refer to anyone who enjoys online shopping.
        </p>
    </div>

    <div class="content_comment_rep">
        <div class="left_avatar left_avatar_rep">
                            <span class="avatar_user"
                                  style="background-image: url('https://i.pinimg.com/564x/92/26/5c/92265c40c8e428122e0b32adc1994594.jpg');"></span>
        </div>
        <div class="right_comment right_comment_rep">
            <p>
                            <span class="title_rep">
                                Siêu Thị Nhật Bản Japana
                            </span>
                <span class="date_rep">
                                 (22/08/2021)
                            </span>
            </p>
            <p class="content_rep">
                I am very happy to refer to anyone who enjoys online shopping.
                I am very happy to refer to anyone who enjoys online shopping.
                I am very happy to refer to anyone who enjoys online shopping.
            </p>
        </div>
    </div>

</div>

<div class="item_bl_group">
    <div class="item_top_comment">
        <div class="left_avatar">
                        <span class="avatar_user"
                              style="background-image: url('https://i.pinimg.com/564x/92/26/5c/92265c40c8e428122e0b32adc1994594.jpg');"></span>
        </div>
        <div class="right_comment">
            <p class="fullname_bl">Carly West</p>
            <p>
                        <span class="rating_bl">
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                        </span>
                <span class="date_bl">
                            (22/08/2021)
                        </span>
            </p>
        </div>
    </div>

    <div class="content_comment">
        <p>
            I am very happy to refer to anyone who enjoys online shopping.
        </p>
    </div>

</div>

<div class="item_bl_group">
    <div class="item_top_comment">
        <div class="left_avatar">
                        <span class="avatar_user"
                              style="background-image: url('https://i.pinimg.com/564x/92/26/5c/92265c40c8e428122e0b32adc1994594.jpg');"></span>
        </div>
        <div class="right_comment">
            <p class="fullname_bl">Carly West</p>
            <p>
                        <span class="rating_bl">
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                        </span>
                <span class="date_bl">
                            (22/08/2021)
                        </span>
            </p>
        </div>
    </div>

    <div class="content_comment">
        <p class="dotdot_content dotdotdot">
            I am very happy to refer to anyone who enjoys online shopping.
            I am very happy to refer to anyone who enjoys online shopping.
            I am very happy to refer to anyone who enjoys online shopping.
        </p>
    </div>

    <div class="content_image_comment">
                    <span class="item_img_bt">
                        <img src="https://japana.vn/uploads/product/imageresize/176x176-1545043795-ehide-bio-150-vien-sieu-thi-nhat-ban-japana-23.jpg"
                             alt="">
                    </span>
        <span class="item_img_bt">
                        <img src="https://japana.vn/uploads/product/imageresize/176x176-1545043795-ehide-bio-150-vien-sieu-thi-nhat-ban-japana-23.jpg"
                             alt="">
                    </span>
        <span class="item_img_bt">
                        <img src="https://japana.vn/uploads/product/imageresize/176x176-1545043795-ehide-bio-150-vien-sieu-thi-nhat-ban-japana-23.jpg"
                             alt="">
                    </span>
        <span class="item_img_bt">
                        <img src="https://japana.vn/uploads/product/imageresize/176x176-1545043795-ehide-bio-150-vien-sieu-thi-nhat-ban-japana-23.jpg"
                             alt="">
                    </span>
    </div>

</div>
