<?php if (!empty($total_image)) {
    ?>

    <div class="review-images">
        <div class="review-images-heading">Tất cả hình ảnh (<?php echo $total_image; ?>)</div>
        <div class="review-images-inner">
            <?php
            if (!empty($list_image)) {
                foreach ($list_image as $key => $image) {
                    $img_load = PATH_IMAGE_COMMENT . $image;
                    ?>
                    <div class="review-images-item">
                        <div class="review-images-img"
                             style="background-image: url(&quot;<?php echo $img_load; ?>&quot;);"></div>
                        <?php
                        if ($key == 3) {
                            if ($total_image > 4) {
                                $img_rest = $total_image - 4;
                                if (!empty($img_rest)) {
                                    ?>
                                    <div class="review-images-total">+<?php echo $img_rest; ?></div>
                                    <?php
                                }
                            }
                            break;
                        }
                        ?>
                    </div>
                    <?php

                    if ($key == 3) {
                        break;
                    }
                }
            }
            ?>
        </div>
    </div>

    <div style="display: none;">
        <?php
        if (!empty($list_image)) {
            foreach ($list_image as $key => $image) {
                $img_load=PATH_IMAGE_COMMENT . $image;
                ?>
                <div class="show_comment_img" data-fancybox="gallery" href="<?php echo $img_load; ?>">
                </div>
                <?php
            }
        }
        ?>
    </div>

    <?php
} ?>