<div class="list_bl_box">
    <?php
    if (!empty($list_comment)) {
        foreach ($list_comment as $item) {
            $fullname = trim($item['fullname']);
            $hoten_array = explode(" ", $fullname);
            $lastname = $hoten_array[count($hoten_array) - 1];
            $firstCharacterName = mb_substr($lastname, 0, 1);
            $firstCharacterName =mb_strtoupper($firstCharacterName);
            ?>
            <div class="item_bl_group">
                <div class="item_top_comment">
                    <div class="left_avatar">
                      <span class="avatar_user">
                            <span class="title_name">
                                <?php echo $firstCharacterName; ?>
                            </span>
                        </span>
                    </div>
                    <div class="right_comment">
                        <p class="fullname_bl"><?php echo $item['fullname']; ?></p>
                        <p>
                        <span class="rating_bl rating-stars" data-stars="<?php echo $item['rate']; ?>">
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                        </span>
                            <span class="date_bl">
                            (
                                <?php echo date("d/m/Y", strtotime($item['created'])); ?>)
                        </span>
                        </p>
                    </div>
                </div>

                <div class="content_comment">
                    <p class="dotdot_content dotdotdot">
                        <?php echo utf8_decode($item['comments']); ?>
                    </p>
                </div>
                <?php if (!empty($item['images'])) {
                    $image = json_decode($item['images'], true);
                    ?>
                    <div class="content_image_comment">
                        <?php foreach ($image as $img) { ?>
                            <span class="item_img_bt" data-fancybox="gallery" href="<?php echo PATH_IMAGE_COMMENT.$img; ?>" style="cursor: pointer">
                        <img src="<?php echo PATH_IMAGE_COMMENT . $img; ?>"
                             alt="Hình ảnh đánh giá">
                    </span>
                        <?php } ?>
                    </div>
                <?php } ?>

                <?php
                /** for admin reply comment*/
                if (!empty($list_comment_rep[$item['id']])) {
                    $list_comment_rep_item = $list_comment_rep[$item['id']];
                    foreach ($list_comment_rep_item as $item_rep) {
                        ?>
                        <div class="content_comment_rep">
                            <div class="left_avatar left_avatar_rep">
                            <span class="avatar_user"
                                  style="background-image: url('https://japana.vn/assets/frontend/assets/images/favicon.png');"></span>
                            </div>
                            <div class="right_comment right_comment_rep">
                                <p>
                            <span class="title_rep">
                                Siêu Thị Nhật Bản Japana
                            </span>
                                    <span class="date_rep">
                                 (<?php echo date("d/m/Y", strtotime($item_rep['created'])); ?>)
                            </span>
                                </p>
                                <p class="content_rep">
                                    <?php echo utf8_decode($item_rep['comments']); ?>
                                </p>
                            </div>
                        </div>
                    <?php }
                } ?>
            </div>

        <?php }
    }else{
        ?>
        <div class="empty_comment_result">
            <div class="icon_bad">
                <span></span>
            </div>
            <div class="text_empty text-center">
                <p>Không tìm thấy nhận xét phù hợp</p>
            </div>
        </div>
        <style>
            .pagination_comment{
                display: none;
            }
        </style>
    <?php
    }
    ?>
</div>
