<?php
    use Zend\Session\Container;

    $view = $this->viewModel()->getCurrent()->getChildren(); 
?>
<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, minimal-ui" />
    <?php echo $this->headTitle();?>
    <?php echo $this->headMeta();?>
    <?php
      echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' =>  URL_ASSET."frontend/assets/images/favicon.png"))
    ?>
    <meta name="google-site-verification" content="UdE5nNyjcvQdIcW4dez9fUO4CG0zVMkbTErLVnR1hbw" /> 
	<!--include-css-->
	<link rel="stylesheet" href="<?php echo URL_FRONTEND;?>plugins/bootstrap/css/bootstrap.min.css" />
	<link rel="stylesheet" href="<?php echo URL_FRONTEND;?>plugins/font-awesome/css///cdn.materialdesignicons.com/2.1.19/css/materialdesignicons.min.css" />
	<link rel="stylesheet" href="<?php echo URL_FRONTEND;?>plugins/themify-icons/themify-icons.css" />
	<link rel="stylesheet" href="<?php echo URL_FRONTEND;?>plugins/jquery-ui/jquery-ui.min.css" />
	<link rel="stylesheet" href="<?php echo URL_FRONTEND;?>plugins/animate.css" />
	<link rel="stylesheet" href="<?php echo URL_FRONTEND;?>plugins/hover.css" />
	<link rel="stylesheet" href="<?php echo URL_FRONTEND;?>plugins/libs.css" />
	<link rel="stylesheet" href="<?php echo URL_FRONTEND;?>plugins/normalize.css" />
	<link rel="stylesheet" href="<?php echo URL_FRONTEND;?>css/all-page.css?v=11">
  <link rel="stylesheet" href="//cdn.materialdesignicons.com/2.1.19/css/materialdesignicons.min.css" />
	<!--/.include-css-->

	<!--include-font-->
	<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500&amp;subset=vietnamese" rel="stylesheet" />
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600&amp;subset=vietnamese" rel="stylesheet" />
	<!--/.include-font-->
	<!--include-js-->
	<script src="<?php echo URL_FRONTEND;?>plugins/jquery-3.3.1.min.js"></script>
	<script  src="<?php echo URL_FRONTEND;?>plugins/bootstrap/js/bootstrap.min.js"></script>
    
    <script>
        $(document).ready(function() {
            $(window).keydown(function(event){
              if(event.keyCode == 13) {
                event.preventDefault();
                return false;
              }
            });
        });
    </script>
<!-- Google Tag Manager -->
<script>
if(navigator.userAgent.indexOf("Speed Insights") == -1) { 
  (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-55PCTT2');
}
</script>
</head>
<body>
<?php if (!isset($_SERVER['HTTP_USER_AGENT']) || stripos($_SERVER['HTTP_USER_AGENT'], 'Speed Insights') === false): ?>
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-55PCTT2"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<?php endif; ?>
    <div class="site-container">
        <?php echo $this->content;?>
    </div>
    <?php $this->userlogin();?>
	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
	<script src="<?php echo URL_FRONTEND;?>plugins/countdown/jquery.countdown.min.js"></script>
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v2.6&appId=626517987552557";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
    <div class="fb-customerchat" page_id=1243228842376892></div>
    
    <?php
    $session = new Container("cart");
    $session->setExpirationSeconds(TIME_SESSION);
    
    if(!empty($session->data_thank)){
    
    $list = json_decode($session->data_thank,true);
    $idCart = $session->idCart;
    $total = $session->total;
    $vanchuyen = $session->vanchuyen;
    
    if(empty($vanchuyen)){
        $vanchuyen = 0;
    }
?>
	<script>
        dataLayer.push({
      	  'ecommerce': {
      	    'purchase': {
      	      'actionField': {
      	        'id': '<?php echo $idCart;?>',                        
      	        'affiliation': 'Siêu thị nhật bản Japana',
      	        'revenue': '<?php echo $total;?>',                 
      	        'tax':'0',
      	        'shipping': '<?php echo $vanchuyen;?>',
      	        'coupon': 'SUMMER_SALE'
      	      },
      	      'products': [<?php $count = count($list);
      	      $i = 0;
              foreach ($list as $key => $value){?>{                           
      	        'name': '<?php echo $value["name"]?>',
      	        'id': '<?php echo $value["id"]?>',
      	        'price': '<?php echo $value["price_market"];?>',
      	        'brand': '<?php echo $session->list_id_product[$value["id"]]["brand"]?>',
      	        'category': '<?php echo $session->list_id_product[$value["id"]]["category"]?>',
      	        'variant': 'Gray',
      	        'quantity': <?php echo $value["sl"];?>,
      	        'coupon': ''
              }<?php if(($i + 1) < $count ){
                  echo ",";
              } $i++; }?>]
      	    }
      	  }
      	});
 	</script>
<?php }?>
    
</body>
</html>