<style>
    .hero-slider {
        position: relative;
        display: none;
        float: left;
        width: 100%
    }

    .hero-slider .item a {
        width: 100%
    }

    .hero-slider .item img {
        width: 100%;
        display: inline-block;
        height: auto
    }

    .hero-slider .slick-dots {
        padding: 0;
        list-style: none;
        text-align: center;
        width: 100%;
        margin-top: -20px;
        margin-bottom: 20px;
        border-bottom: 1px solid #e3e3e3
    }

    .hero-slider .slick-dots button {
        line-height: 0;
        display: block;
        width: 5px;
        height: 5px;
        padding: 3px;
        cursor: pointer;
        color: transparent;
        border: 3px solid rgba(255, 255, 255, .5);
        outline: none;
        background: transparent;
        border-radius: 100%
    }

    .hero-slider .slick-dots li {
        display: inline-block;
        padding: 0;
        cursor: pointer
    }

    .hero-slider .slick-dots .slick-active {
        border-bottom: 2px solid #bb0029
    }

    .pager-item {
        font-family: 'Roboto', sans-serif;
        font-weight: 400;
        font-size: 16px;
        color: #999;
        display: inline-block;
        width: 100%;
        border-right: 2px solid #999;
        padding: 0 26px;
        margin: 10px 0
    }

    .hero-slider .slick-dots .slick-active .pager-item,
    .pager-item:hover {
        color: #333
    }

    .hero-slider .slick-dots li:last-child .pager-item {
        border-right: 0
    }
</style>
<div class="hero-slider">
	<?php foreach ($multi_images["desktop"] as $key => $value){ ?>
		<?php
		if(strtotime($value["begin_date"][0]) <= strtotime(date("d-m-Y H:i")) && strtotime($value["end_date"][0]) >= strtotime(date("d-m-Y H:i"))){
		?>
		<div class="item" data-title="<?php echo $value["name_images"][0]?>">
			<?php
			    $array = explode("-", $value["upload"][0]);
        		$time = $array[0];
        		$folder_date = PATH_IMAGE_BLOCK.date('Y',$time)."/".date('m',$time)."/".date('d',$time)."/".$value["upload"][0];
    		?>
			<a href="<?php echo $value["link_images"][0];?>" title="<?php echo $value["name_images"][0];?>">
			    <img src="<?php echo $folder_date;?>" alt="<?php echo $value["name_images"][0];?>">
			</a>
		</div>
	<?php }}?>
</div>
<script>
    jQuery(document).ready(function(){initBannerSlider()});var initBannerSlider=function(){jQuery('.hero-slider').not('.slick-initialized').slick({autoplay:!0,fade:!0,cssEase:'linear',speed:1000,dots:!0,autoplaySpeed:3000,nextArrow:'',prevArrow:'',customPaging:function(slider,i){var title=$(slider.$slides[i]).data('title');return'<a class="pager-item" title="'+title+'"> '+title+' </a>'},})}
</script>