<?php
    $url = $arrayParam["url"];
    $slug_url = $arrayParam["slug_url"];
	if($this->first != $this->current && $this->first > 0){		
	    $strPageStart = '<li><a class="pagin-item" name="pagination" value="" href="' . $url."1" .$slug_url. '"><i class="fa fa-angle-double-left" aria-hidden="true"></i></a></li>';
	}else{
		$strPageStart = '';
	}
	if(isset($this->previous)){
	    $linkPrevious 	='<li><a class="pagin-item" name="pagination" value="'.$this->previous .'" href="' . $url . $this->previous .$slug_url. ' "><i class="fa fa-angle-left" aria-hidden="true"></i></a></li>';
	}else{
		$linkPrevious 	='';
	}
	if(isset($this->next)){
	    $linkNext 		=' <li><a class="pagin-item" name="pagination" value="' .  $this->next . $slug_url.'" href="' . $url . $this->next .$slug_url. '"><i class="fa fa-angle-right" aria-hidden="true"></i></a></li>';
	}else{
		$linkNext 		='';
	}
	if($this->last != $this->current && $this->last > 0){
	    $strPageEnd = '<li><a class="pagin-item" name="pagination" value="' .  $this->pageCount . $slug_url.'" href="' . $url . $this->pageCount .$slug_url. '"><i class="fa fa-angle-double-right" aria-hidden="true"></i></a></li>';
	}else{
		$strPageEnd = '';
	}
	$strPage  = '';
	foreach ($this->pagesInRange as $key){
		if($this->current != $key){
		    $strPage .= '<li><a class="pagin-item" name="pagination" value="' . $key . '" href="' . $url . $key .$slug_url. '">' . $key .'</a></li>';
		}else{
			$strPage .= '<li class="active"><a class="pagin-item" name="pagination" href="javascript:void(0)">' . $key . '</a></li>';
		}
	}
	$page = $strPageStart . $linkPrevious . $strPage . $linkNext . $strPageEnd;
?>
<?php if($this->last > 1){?>
    <div class="text-center">
         <ul class="paginav">
    		<?php echo $page;?>                   
    	</ul>
    </div>
<?php }?>  
<style>
/*******************PAGINATION*******************/
.paginav{
	margin-top: 0;
	clear: both;
	display: -webkit-box;
	display: -ms-flexbox;
	display: flex;
		-webkit-box-align: center;
			-ms-flex-align: center;
				align-items: center;
		-webkit-box-pack: center;
			-ms-flex-pack: center;
				justify-content: center;
}

.paginav li{
	background: #fff;
    border: 1px solid #e3e3e3;
    width: 35px;
    height: 35px;
    border-radius: 4px;
    margin: 0 4px;
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-align: center;
    -ms-flex-align: center;
            align-items: center;
    -webkit-box-pack: center;
    -ms-flex-pack: center;
            justify-content: center;
}

.first-pag .pagin-item, .last-pag .pagin-item, .more .pagin-item{
  font-family: 'Roboto' , sans-serif;
  font-weight: 400;
  font-size: 20px;
  border: 0 !important;
}

.paginav .pagin-item {
  	color: #666666;
  	font-weight: 400;
  	font-size: 16px;
    padding: 10px 13px;
}

.paginav .active{
	background: #e62e6b;
}
.paginav .active a{
  	color: #fff;
}

.paginav li,.paginav .active:hover{
  	color: #e62e6b;
	background: #fff;
}

.paginav .active:hover a,.paginav a:hover{
  color: #e62e6b;
}
/*******************END_PAGINATION*******************/    
</style>
