<link href="<?php echo URL_ASSET?>frontend/assets/css/paginationCustom.css" rel="stylesheet" type="text/css" />
<?php
    $url = $arrayParam["url"];
    $slug_url = $arrayParam["slug_url"];
	if($this->first != $this->current && $this->first > 0){		
	    $strPageStart = '<li class="page-item"><a class="page-link page-arrow" name="pagination" value="" href="' . $url."1" .$slug_url. '"><i class="fa fa-angle-double-left" aria-hidden="true"></i></a></li>';
	}else{
		$strPageStart = '';
	}
	if(isset($this->previous)){
	    $linkPrevious 	='<li class="page-item"><a class="page-link page-arrow" name="pagination" value="'.$this->previous .'" href="' . $url . $this->previous .$slug_url. ' "><i class="fa fa-angle-left" aria-hidden="true"></i></a></li>';
	}else{
		$linkPrevious 	='';
	}
	if(isset($this->next)){
	    $linkNext 		=' <li class="page-item"><a class="page-link page-arrow" name="pagination" value="' .  $this->next . $slug_url.'" href="' . $url . $this->next .$slug_url. '"><i class="fa fa-angle-right" aria-hidden="true"></i></a></li>';
	}else{
		$linkNext 		='';
	}
	if($this->last != $this->current && $this->last > 0){
	    $strPageEnd = '<li class="page-item"><a class="page-link page-arrow" name="pagination" value="' .  $this->pageCount . $slug_url.'" href="' . $url . $this->pageCount .$slug_url. '"><i class="fa fa-angle-double-right" aria-hidden="true"></i></a></li>';
	}else{
		$strPageEnd = '';
	}
	$strPage  = '';
	foreach ($this->pagesInRange as $key){
		if($this->current != $key){
		    $strPage .= '<li class="page-item"><a class="page-link" name="pagination" value="' . $key . '" href="' . $url . $key .$slug_url. '">' . $key .'</a></li>';
		}else{
			$strPage .= '<li class="page-item active"><a class="page-link" name="pagination" href="javascript:void(0)">' . $key . '</a></li>';
		}
	}
	$page = $strPageStart . $linkPrevious . $strPage . $linkNext . $strPageEnd;
?>
<?php if($this->last > 1){?>
	<div class="box-pagination">
		<ul class="pagination">
			<?php echo $page;?>                   
		</ul>
		<div class="custom-select-option">
			<input name="limit" id="limit" value="<?php echo $arrayParam['limit']?>" type="hidden">
			<select class="custom-select">
				<option value="20" <?php if(($arrayParam['limit'])==20) {?>selected<?php }?>>20</option> 
				<option value="50" <?php if(($arrayParam['limit'])==50) {?>selected<?php }?>>50</option>
				<option value="100" <?php if(($arrayParam['limit'])==100) {?>selected<?php }?>>100</option>
			</select> 
			<i class="icon-triangle-down"></i>
		</div>
	</div>
<?php }?>
<script>
	$('.custom-select').on('change', function (e) {
		var optionSelected = $("option:selected", this);
		jQuery("#limit").val(this.value);
		jQuery("#filter_from").submit();
	});
</script>