<style>
.sidebar-detail{margin-top:0;width:300px;padding-left:30px;float:right}.sidebar-detail>.info-detail{border:0;padding:0;margin-top:3px}.side-products{border:0!important;padding:0!important}.side-products .title-side{margin-bottom:0;background:#e3e3e3;padding:5px 15px!important}.side-products .title-side span{font-family:'Open Sans',sans-serif;font-weight:400;font-size:16px;color:#333;border-left:2px solid #bb0029;padding-left:5px}
</style>
<?php
if(!empty($sanphamlienquan)) {
    ?>
    <aside class="sidebar sidebar-primary sidebar-detail">
        <section class="widget side-products">
            <h3 class="title-side">
                <span>Có thể bạn quan tâm</span>
            </h3>
            <div class="list-side-pro">
        <?php
            for($i = 0; $i < count($sanphamlienquan); $i++) {
                $array = explode("-", $sanphamlienquan[$i]["images"]);
                $time = date("Y/m/d",$array[0])."/";
                $images = PATH_IMAGE_PRO.$time.$sanphamlienquan[$i]["images"];
                $url = URL.$sanphamlienquan[$i]["slug_vi"]."-sp-".$sanphamlienquan[$i]["id"];
            ?>
                <div class="item item-product-custom">
                    <div class="box-img">
                        <a href="<?php echo $url; ?>" title="<?php echo $sanphamlienquan[$i]["name_vi"];?>">
                            <img src="<?php echo $images; ?>" alt="<?php echo $sanphamlienquan[$i]["name_vi"];?>">
                        </a>
                    </div>
                    <div class="detail">
                        <h3 class="title"><a href="<?php echo $url; ?>" title="title"><?php echo $this->cutString($sanphamlienquan[$i]["name_vi"],60);?></a></h3>
                        <div class="other">
                            <div class="price">
                                <?php if(intval($price_promotion) > 0){ ?>
                                <p class="new-price"><?php echo number_format(intval($price_promotion),"0",",",".");?> đ</p>
                                <p class="old-price"><?php echo number_format($sanphamlienquan[$i]["price"],0,"",".");?> đ</p>
                                <?php }else{ ?>
                                <p class="new-price" style="width: 100%; text-align: right;"><?php echo number_format($sanphamlienquan[$i]["price"],0,"",".");?> đ</p>
                                <?php } ?>
                            </div>
                            <!--<button onclick="addCart(
                                    '<?php /*echo $sanphamlienquan[$i]["id"]*/?>',
                                    1,
                                    '<?php /*echo $images;*/?>',
                                    '<?php /*echo $sanphamlienquan[$i]["name_vi"];*/?>',
                                    '<?php
/*                                            if(intval($price_promotion) > 0){
                                                echo $price_promotion;
                                            }else{
                                                echo $sanphamlienquan[$i]["price"];
                                            }
                                      */?>',
                                    '<?php /*echo $url;*/?>',
                                    '<?php /*echo $sanphamlienquan[$i]["sku"];;*/?>',
                                    '<?php /*echo $sanphamlienquan[$i]["kg"];*/?>'
                                    )" type="button" class="muahang btn-buy convert-background-color-15B02A"><img src="assets/images/btn-mua.png" alt="buy">
                            </button>-->
                        </div>
                    </div>

                    <!-- <div class="action">
                        <ul>
                            <li>
                                <a href="<?php echo $url; ?>" title="<?php echo $sanphamlienquan[$i]["name_vi"]; ?>" class="btn d-flex align-items-center justify-content-center btn-chitiet-custom" tabindex="0">
                                    CHI TIẾT
                                </a>
                            </li>
                            <li>
                                <button class="muahang cls-btn-product-to-cart btn-themvaogio-custom"
                                        data-id="<?= $sanphamlienquan[$i]["id"] ?>"
                                        data-image="<?= $images ?>"
                                        data-name="<?= $sanphamlienquan[$i]["name_vi"] ?>"
                                        data-price_market="<?= intval($price_promotion) > 0 ? $price_promotion : $sanphamlienquan[$i]["price"]; ?>"
                                        data-url="<?php echo $url; ?>"
                                        data-sku="<?php echo $sanphamlienquan[$i]["sku"]; ?>"
                                        data-kg="<?php echo $sanphamlienquan[$i]["kg"]; ?>"
                                        data-text_qt=""
                                        data-images_qt=""
                                >Thêm vào giỏ</button>

                            </li>
                        </ul>
                    </div> -->


                </div>
                <!--item-->
            <?php
        }//end for
    ?>

            </div>
        </section>
    </aside>
    <?php
}//end fun
    ?>