<?php foreach ($list as $key => $value){
    if(!empty($value["images"])) {
        $array = explode("-", $value["images"]);
        $time = date("Y/m/d", $array[0]) . "/";
        $images = PATH_IMAGE_RESIZE_PRO . "176x176-".$value["images"];
    }else{
        $images ="";
    }
    $url = URL . $value["slug_vi"] . "-sp-" . $value["id"];
    $price_promotion = "";
    $hienthi = 0;
    $text_qt = "";
    $images_qt = "";
    if( $value["status_product"] == 1 && strtotime($value["date_start"]) <= strtotime(date("y-m-d")) && strtotime($value["date_end"]) >= strtotime(date("y-m-d"))){
        if(!empty($value["text_pt"])){
            $price_promotion = $value["price"] - ($value["text_pt"]*$value["price"]/100);
            $hienthi = 1;
        }
        if(!empty($value["text_vnd"])){
            $price_promotion = $value["price"] - $value["text_vnd"];
            $hienthi = 1;
        }
    }
    ?>

    <div class="item item-product-custom" style="width: 100%; display: inline-block;">
        <div class="box-img">
            <a href="<?php echo $url; ?>" title="<?php echo $value["name_vi"]; ?>">
                <img src="<?php echo $images; ?>" alt="<?php echo $value["name_vi"]; ?>">
            </a>
            <?php
            if( $value["status_product"] == 1 && strtotime($value["date_start"]) <= strtotime(date("y-m-d")) && strtotime($value["date_end"]) >= strtotime(date("y-m-d"))){?>
                <?php if(!empty($value["text_pt"])){?>
                    <div class="block-sale">
                        <img src="<?php echo $km_images;?>" alt="hình">
                        <span class="sale">-<?php echo $value["text_pt"]?>%</span>
                    </div>
                <?php }?>
                <?php if(!empty($value["text_qt"])){?>
                    <div class="block-sale2">
                        <img src="<?php echo $km_images_qt;?>" alt="hình">
                    </div>
                    <?php
                    $text_qt = $value["text_qt"];
                    $images_qt = $km_images_qt;
                    ?>
                <?php }?>
            <?php }?>
            <?php if($value["status_product_k"] == 1 && strtotime($value["date_start_k"]) <= strtotime(date("y-m-d")) && strtotime($value["date_end_k"]) >= strtotime(date("y-m-d"))){?>
                <?php if(!empty($list_product[$value["id"]])){?>
                    <div class="block-sale3">
                        <img src="<?php echo $list_product[$value["id"]];?>" alt="hình">
                    </div>
                <?php }?>
            <?php }?>
        </div>
        <div class="detail">
            <h3 class="title">
                <a href="<?php echo $url; ?>" title="<?php echo $value["name_vi"]; ?>"><?php echo $this->cutString($value["name_vi"],60); ?></a>
            </h3>
            <ul class="box-price">
                <?php if (intval($hienthi) > 0) { ?>
                    <li class="price">
                        <span><?php echo number_format(intval($price_promotion), "0", ",", "."); ?> đ</span>
                    </li>
                    <li class="old-price">
                        <span><?php echo number_format($value["price"], 0, "", "."); ?> đ</span>
                    </li>
                <?php } else { ?>
                    <li class="price" style="width: 100%">
                        <span><?php echo number_format($value["price"], 0, "", "."); ?> đ</span>
                    </li>
                <?php } ?>
            </ul>
        </div>
    </div>

    <?php
}//end for
?>