<?php
    if (!empty($detail["images"])) {
        $array = explode("-", $detail["images"]);
        $time = date("Y/m/d", $array[0]) . "/";
        $url_image = PATH_IMAGE_PRO . $time . $detail["images"];
        $url_image_168 = PATH_IMAGE_PRO . $time . "168x168-" . $detail["images"];
        $img_product["images"] = $detail["images"];
    } else {
        $url_image = "";
    }

    $price_promotion = "";
    $hienthi = 0;
    $text_qt = "";
    $images_qt = "";
    if ($detail["status_product"] == 1 && strtotime($detail["date_start"]) <= strtotime(date("y-m-d")) && strtotime($detail["date_end"]) >= strtotime(date("y-m-d"))) {
        if (!empty($detail["text_pt"])) {
            $price_promotion = $detail["price"] - ($detail["text_pt"] * $detail["price"] / 100);
            $hienthi = 1;
        }
        if (!empty($detail["text_vnd"])) {
            $price_promotion = $detail["price"] - $detail["text_vnd"];
            $hienthi = 1;
        }
    }
?>
<h2 id="title-bought-together">Mua cùng giảm thêm</h2>

<div class="item-bought-together box-check ">
    <?php
    $countList = 0;
    foreach ($listProductInCategory as $key => $value) :
        if($value["status_num"] == 1) :
            $countList++;
            $url1 = URL . $value["slug_vi"] . "-sp-" . $value["id_product_in_category"];
            if(!empty($value["images"])){
                $array = explode("-", $value["images"]);
                $time = date("Y/m/d",$array[0])."/";
                $images = PATH_IMAGE_RESIZE_PRO."38x38-".$value["images"];
            }else{
                $images = "";
            }

            $hienthi1 = 0;
            $priceNew = $value["price"];
            $price_promotion1 = "";
            $text_qt = "";
            $images_qt = "";
            if ($value["status_product"] == 1 && strtotime($value["date_start"]) <= strtotime(date("y-m-d")) && strtotime($value["date_end"]) >= strtotime(date("y-m-d"))) {
                if (!empty($value["text_pt"])) {
                    $price_promotion1 = $value["price"] - ($value["text_pt"] * $value["price"] / 100);
                    $hienthi1 = 1;
                }
                if (!empty($value["text_vnd"])) {
                    $price_promotion1 = $value["price"] - $value["text_vnd"];
                    $hienthi1 = 1;
                }
                if (!empty($value["text_qt"])) {
                    $text_qt = $value["text_qt"];
                    $images_qt = $detail['km_images_qt'];
                }
            }
            if($price_promotion1 != ""){
                $priceNew = $price_promotion1;
            }
            ?>

            <div class="box-bought-together-item">
                <div class="box-left-bought-together">
                    <label class="check-custom">
                        <div class="box-images">
                            <a href="<?= $url1 ?>" title="<?= $value["name_vi"] ?>" class="image ">
                                <img src="<?php echo $images;?>" alt="<?= $value["name_vi"] ?>">
                            </a>
                        </div>

                        <p class="product-name-bought-together">
                            <?= $value["name_vi"] ?>
                        </p>
                        <input type="checkbox" name="" onclick="changeProductTogether(<?= $value["id_product_in_category"] ?>, <?= $priceNew ?>)" id="product-<?= $value["id_product_in_category"] ?>" data-id="<?= $value["id_product_in_category"] ?>" data-price="<?= $value["price"] ?>" class="checkbox-bought-together" checked>
                        <span class="checkmark"></span>
                    </label>
                </div>

                <div class="box-right-bought-together">
                    <?php if (intval($hienthi1) > 0) { ?>
                        <p class="price-bought-together"> <?php echo number_format(intval($price_promotion1), "0", ",", "."); ?>đ</p>
                        <p class="old-price-bought-together"><?php echo $price = number_format($value["price"], "0", ",", "."); ?> đ</p><?php } else { ?>
                        <p class="price-bought-together"><?= number_format($value["price"], "0", ",", "."); ?>đ </p>
                    <?php } ?>

                </div>

            </div>

        <?php
        endif;
    endforeach;
    ?>
</div>
<div id="box-bought-together-total">
    <span id="title-bought-together-total">Tổng cộng: </span>
    <p id="bought-together-price-total"> <?= number_format($purchaseTotalPrice, "0", ",", "."); ?> đ </p>
    <br />
    <button
            id="push-to-cart-all"
            data-id="<?= $detail["id"] ?>"
            data-image="<?= $url_image_168 ?>"
            data-name="<?= addslashes($detail["name_vi"]) ?>"
            data-price_market="<?= intval($price_promotion) > 0 ? $price_promotion : $detail["price"];?>"
            data-url="<?php echo $url; ?>"
            data-sku="<?php echo $detail["sku"]; ?>"
            data-kg="<?php echo $detail["kg"]; ?>"
            data-text_qt="<?= $text_qt ? $text_qt : '' ;?>"
            images_qt="<?= $images_qt ? $images_qt : '' ;?>"
    >
        Thêm tất cả vào giỏ
    </button>
</div>

<input type="hidden" id="purchase-total-price" value="<?= $purchaseTotalPrice ?>">
<input type="hidden" id="arrProductIdInCategory" value='<?= $arrProductIdInCategory ?>'>
<input type="hidden" id="listProductInCategoryTotal" value='<?= $countList; ?>'>
<input type="hidden" id="jsonProductInCategory" value='<?= $jsonProductInCategory;?>'>