<style>
    .map{position:relative}.box-contact{width:470px;position:absolute;top:0;background:rgba(0,0,0,.7);text-align:center;padding:32px 30px 35px;top:50%;right:95px;-webkit-transform:translate(0,-50%);-ms-transform:translate(0,-50%);transform:translate(0,-50%)}.box-contact .title{font-family:'Roboto',sans-serif;font-weight:500;font-size:22px;color:#fff}.box-contact .sapo{font-family:'Roboto',sans-serif;font-weight:400;font-size:14px;color:#fff;margin-bottom:28px}.box-contact .ipt-contact{font-family:'Roboto',sans-serif;font-weight:400;font-size:14px;font-style:italic;border-radius:0;margin-bottom:24px}.btn-contact{background:#bb0029;padding:16px 0;color:#fff;font-family:'Roboto',sans-serif;font-weight:500;font-size:16px;text-align:center;border:0;width:100%}.btn-contact:hover{color:#bb0029;background:#fff}
</style>
<?php
$this->headTitle ("JAPANA");
$this->headMeta ()
    ->setProperty('og:title', "Liên hệ")
    ->setProperty("og:type", "website")
    ->setProperty("og:site_name", "japana.vn");
?>
<?php
$this->header(array( "adapter" => $adapter,"active" => $active));
?>
    <div class="site-inner">
        <div class="content-sidebar-wrap">
            <main class="contact content">
                <div class="map">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3919.23029251409!2d106.62277041418271!3d10.79366606182825!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752bff61bf4cb9%3A0x437ac5fb84a0c8cf!2zU2nDqnUgVGjhu4sgTmjhuq10IELhuqNuIE9ubGluZSAtIEphcGFuYS52bg!5e0!3m2!1svi!2s!4v1519717652110" width="100%" height="640" style="border:0" allowfullscreen></iframe>
                    <div class="container">
                        <form method="POST" name="frmContact" id="frmContact">
                            <div class="box-contact form-group">
                                <h3 class="title">LIÊN HỆ VỚI CHÚNG TÔI</h3>
                                <p class="sapo">Để lại lời nhắn và chúng tôi sẽ giúp đỡ bạn nhanh nhất có thể</p>
                                <input maxlength="120" type="text" name="name_contact" id="name_contact" placeholder="Tên" class="ipt-contact form-control ">
                                <input maxlength="120" type="email" name="email_contact" id="email_contact" placeholder="Email" class="ipt-contact form-control">
                                <input maxlength="11" type="tel" name="phone_contact" id="phone_contact" placeholder="Số điện thoại" class="ipt-contact form-control">
                                <textarea maxlength="250" rows="5" name="notes" id="notes" placeholder="Bạn đang lo lắng điều gì?" class="ipt-contact form-control"></textarea>
                                <p class="sapo"><?php echo $mess ?></p>
                                <button type="button" class="btn-contact" onclick="contact.sendcontact();">Gửi</button>
                            </div>
                        </form>
                    </div>
                </div>
            </main>
        </div>
    </div>
<?php
$this->footer(array( "adapter" => $adapter));
?>
<script>
    var contact={sendcontact:function(){var name=$("#name_contact").val();var email=$("#email_contact").val();var tel=$("#phone_contact").val();var notes=$("#notes").val();var filter=/^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;if($.trim(name)==''){$("#name_contact").css("border","2px solid red");$("#name_contact").attr('placeholder','Báº¡n chÆ°a nháº­p há» tĂªn');return!1}else{$("#fullname").css("border","1px solid #ccc")}
if($.trim(email)==''){$("#email_contact").css("border","2px solid red");$("#email_contact").attr('placeholder','Báº¡n chÆ°a nháº­p email');return!1}else{$("#email_contact").css("border","1px solid #ccc")}
if(!filter.test(email)){$("#email_contact").css("border","2px solid red");$('#email_contact').attr('placeholder','Email khĂ´ng há»™p lá»‡');return!1}else{$("#email_contact").css("border","1px solid #ccc")}
if($.trim(tel)==''){$("#phone_contact").css("border","2px solid red");$("#phone_contact").attr('placeholder','Báº¡n chÆ°a nháº­p sá»‘ Ä‘iá»‡n thoáº¡i');return!1}else{$("#phone_contact").css("border","1px solid #ccc")}
if($.trim(notes)==''){$("#notes").css("border","2px solid red");$("#notes").attr('placeholder','Vui lĂ²ng Ä‘á»ƒ láº¡i tin nháº¯n');return!1}
$("#frmContact").submit()}}
</script>