
<style>
    .slide-pro {
        display: inline-block;
        width: 100%;
        margin-bottom: 0;
        margin-top: 11px;
    }



    /*.slide-pro .slick-arrow {*/
    /*    position: absolute;*/
    /*    font-size: 40px;*/
    /*    top: 50%;*/
    /*}*/
    /*.slide-pro .slick-prev {*/
    /*    left: -25px;*/
    /*    z-index: 99;*/
    /*    cursor: pointer;*/
    /*}*/
    /*.slide-pro .slick-next {*/
    /*    right: -25px;*/
    /*    z-index: 99;*/
    /*    cursor: pointer;*/
    /*}*/


    .slide-pro .slick-arrow {
        position: absolute;
        top: 30%;
        font-size: 40px;
    }
    .slide-pro .slick-prev,
    .slide-pro .slick-next {
        color: #000;
        cursor: pointer;
    }
    .slide-pro .slick-prev,
    .slide-pro .slick-next {
        border-radius: 100%;
        border: 1px solid #e3e3e3;
        background: #fff;
        top: 40%;
        width: 40px;
        height: 40px;
        display: -webkit-box !important;
        display: -ms-flexbox !important;
        display: flex !important;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
        -webkit-box-pack: center;
        -ms-flex-pack: center;
        justify-content: center;
        z-index: 20;
        transform: translate(0, 40%);
    }
    .slide-pro .slick-prev {
        left: -18px!important;
    }
    .slide-pro .slick-prev i,
    .slide-pro .slick-next i {
        font-size: 15px;
    }
    .slide-pro .slick-next {
        right: -20px!important;
    }
    .slide-pro .slick-prev:hover,
    .slide-pro .slick-next:hover {
        -webkit-box-shadow: 0 0 1px 2px rgba(0, 0, 0, 0.1);
        box-shadow: 0 0 1px 2px rgba(0, 0, 0, 0.1);
        -webkit-transition: all 0.4s ease-in-out;
        -o-transition: all 0.4s ease-in-out;
        transition: all 0.4s ease-in-out;
    }



    .slide-pro .item {
        margin: 0;
    }
    .slide-pro span i {
        color: #999;
    }
    .title-slide {
        font-family: "Roboto", sans-serif;
        font-weight: 400;
        font-size: 16px;
        color: #2a2a2a;
        border-bottom: 1px solid #bb0029;
        padding-bottom: 4px;
    }
    .slide-pro .item {
        margin: 0;
        float: left;
    }
    .slide-pro .item .box-item {
        border: 1px solid #fff;
        padding-bottom: 8px;
        border-radius: 4px 4px 0 0;
    }
    .slide-pro .item .box-img {
        position: relative;
        text-align: center;
    }
    .slide-pro .item .box-img a {
        display: inline-block;
        height: auto;
        text-align: center;
        width: 180px;
    }
    .slide-pro .item .box-img a img {
        max-width: 100%;
    }
    .slide-pro .item .box-item .detail {
        padding: 0 10px;
    }
    .slide-pro .item .detail .title a {
        font-size: 14px;
        font-family: "Roboto", sans-serif;
        font-weight: 400;
        color: #333;
        min-height: 42px;
        display: inline-block;
        width: 100%;
        line-height: 1.5;
    }
    .slide-pro .item .detail .title a:hover {
        color: #bb0029;
    }
    .slide-pro .item .detail .box-price {
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
        -webkit-box-pack: justify;
        -ms-flex-pack: justify;
        justify-content: space-between;
    }
    .slide-pro .item .detail .box-price .price-sale {
        font-family: "Roboto", sans-serif;
        font-size: 20px;
        font-weight: 400;
        color: #999;
        text-decoration: line-through;
        margin-bottom: 13px;
    }
    .slide-pro .item .detail .box-price .price {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        color: #bb0029;
    }
    .slide-pro .item .detail .box-price .price-sale {
        font-size: 14px;
        margin: 0;
        color: #666;
    }
    .slide-pro .item .detail .box-rate {
        margin: 3px 0 11px;
    }
    .buy-now {
        border: 1px solid #15b02a;
        color: #fff;
        text-transform: uppercase;
        font-size: 24px;
        font-family: "Roboto", sans-serif;
        font-weight: 400;
        background: #15b02a;
        width: 200px;
        height: 50px;
    }
    .buy-now {
        width: 100%;
        height: auto;
        font-size: 18px;
        padding: 10px 0;
        text-transform: none;
        visibility: hidden;
        border-radius: 0 0 4px 4px;
    }
    .list-pro-bottom .item:hover .box-item {
        border: 1px solid #ddd;
    }
    .list-pro-bottom .item:hover .buy-now {
        visibility: visible;
    }
    .box-rate {
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
    }
    .box-rate .count-rate {
        font-size: 14px;
        font-family: "Roboto", sans-serif;
        font-weight: 400;
        color: #666;
        padding-left: 5px;
    }
    .list-pro-bottom .item .detail .box-rate {
        margin: 3px 0 0;
    }
    .block-sale,
    .block-sale2 {
        position: absolute;
        top: 0;
        right: 0;
    }
    .block-sale {
        width: 100%;
        padding: 10px;
        padding-bottom: 0;
        text-align: right;
        padding-left: 0;
    }
    .block-sale2 {
        bottom: 0;
        left: 0;
        top: auto;
        right: auto;
        padding: 10px;
        padding-right: 0;
        padding-top: 0;
        width: 100%;
        text-align: left;
    }
    .block-sale3 {
        top: 0;
        left: 0;
        right: auto;
        text-align: left;
        position: absolute;
        padding-left: 10px;
        padding-top: 10px;
    }
    .block-sale .sale {
        font-family: "Roboto", sans-serif;
        font-size: 13px;
        font-weight: 500;
        color: #fff;
        position: absolute;
        top: 9px;
        right: 10px;
        width: 50px;
        height: 50px;
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
        -webkit-box-pack: center;
        -ms-flex-pack: center;
        justify-content: center;
    }
    .block-sale2 {
        width: 55px;
        height: 55px;
    }
    .block-sale3 {
        width: auto;
        max-height: 55px;
    }
    .block-sale {
        width: 60px;
        height: 60px;
    }
    .block-sale img,
    .block-sale2 img {
        height: auto;
        width: 100%;
    }
    .block-sale3 img {
        max-height: 50px;
        width: auto;
    }

</style>
<div class="container">
<?php
    if (!empty($sanphamgoiy)) {
        ?>
        <div class="list-pro clear box-shadow-global slide-custom">

            <div class="card-header">
                <h2 class="title-item">SẢN PHẨM ĐÃ XEM</h2>
            </div>

            <div class="card-body">
                <div class="list-pro-bottom slide-pro">
                <?php
                for ($i = 0; $i < count($sanphamgoiy); $i++) {
                    $array = explode("-", $sanphamgoiy[$i]["images"]);
                    $time = date("Y/m/d", $array[0]) . "/";
                    $images = PATH_IMAGE_PRO . $time ."268x268-". $sanphamgoiy[$i]["images"];
                    $url = URL . $sanphamgoiy[$i]["slug_vi"] . "-sp-" . $sanphamgoiy[$i]["id"];
                    $price_promotion = "";
                    $hienthi = 0;
                    $text_qt = "";
                    $images_qt = "";
                    if($sanphamgoiy[$i]["status_product"] == 1 && strtotime($sanphamgoiy[$i]["date_start"]) <= strtotime(date("y-m-d")) && strtotime($sanphamgoiy[$i]["date_end"]) >= strtotime(date("y-m-d"))){
                        if(!empty($sanphamgoiy[$i]["text_pt"])){
                          $price_promotion = $sanphamgoiy[$i]["price"] - ($sanphamgoiy[$i]["text_pt"]*$sanphamgoiy[$i]["price"]/100);
                          $hienthi = 1;
                        }
                        if(!empty($sanphamgoiy[$i]["text_vnd"])){
                            $hienthi = 1;
                          $price_promotion = $sanphamgoiy[$i]["price"] - $sanphamgoiy[$i]["text_vnd"];
                        }
                    }

                    ?>

                    <div class="item item-product-custom" style="width: 100%; display: inline-block;">
                        <div class="box-img">
                            <a href="<?php echo $url; ?>" title="<?php echo $sanphamgoiy[$i]["name_vi"]; ?>" tabindex="0">
                                <img src="<?php echo $images; ?>" alt="<?php echo $sanphamgoiy[$i]["name_vi"]; ?>" />
                            </a>
                            <?php
                            if($sanphamgoiy[$i]["status_product"] == 1 && strtotime($sanphamgoiy[$i]["date_start"]) <= strtotime(date("y-m-d")) && strtotime($sanphamgoiy[$i]["date_end"]) >= strtotime(date("y-m-d"))){?>
                                <?php if(!empty($sanphamgoiy[$i]["text_pt"])){?>
                                    <div class="block-sale">
                                        <img src="<?php echo $km_images;?>" alt="hình">
                                        <span class="sale">-<?php echo $sanphamgoiy[$i]["text_pt"]?>%</span>
                                    </div>
                                <?php }?>

                                <?php if(!empty($sanphamgoiy[$i]["text_qt"])){?>
                                    <div class="block-sale2">
                                        <img src="<?php echo $km_images_qt;?>" alt="hình">
                                    </div>
                                    <?php
                                    $text_qt = $sanphamgoiy[$i]["text_qt"];
                                    $images_qt = $km_images_qt;
                                    ?>
                                <?php }?>
                            <?php }?>
                            <?php if($sanphamgoiy[$i]["status_product_k"] == 1 && strtotime($sanphamgoiy[$i]["date_start_k"]) <= strtotime(date("y-m-d")) && strtotime($sanphamgoiy[$i]["date_end_k"]) >= strtotime(date("y-m-d"))){?>
                                <?php if(!empty($list_product[$sanphamgoiy[$i]["id"]])){?>
                                    <div class="block-sale3">
                                        <img src="<?php echo $list_product[$sanphamgoiy[$i]["id"]];?>" alt="hình">
                                    </div>
                                <?php }?>
                            <?php }?>
                        </div>
                        <div class="detail">
                            <h3 class="title">
                                <a href="<?php echo $url; ?>" title="<?php echo $sanphamgoiy[$i]["name_vi"]; ?>" tabindex="0">
                                    <?php echo $this->cutString($sanphamgoiy[$i]["name_vi"],50); ?>
                                </a>
                            </h3>
                            <ul class="box-price">

                                <?php if (intval($price_promotion) > 0) { ?>
                                    <p class="price-sale"><?php echo number_format($sanphamgoiy[$i]["price"], 0, "", "."); ?>
                                        đ</p>
                                    <p class="price"><?php echo number_format(intval($price_promotion), "0", ",", "."); ?>
                                        đ</p>
                                <?php } else { ?>
                                    <p class="price" style="width: 100%; text-align: right;"><?php echo number_format($sanphamgoiy[$i]["price"], 0, "", "."); ?>
                                        đ</p>
                                <?php } ?>

                            </ul>
                        </div>
                        <!-- <div class="action">
                            <ul>
                                <li>
                                    <a
                                        href="<?php echo $url; ?>"
                                        title="Chi tiết"
                                        class="btn d-flex align-items-center justify-content-center btn-chitiet-custom"
                                        tabindex="0"
                                    >
                                        CHI TIẾT
                                    </a>
                                </li>
                                <li>
                                    <button class="muahang cls-btn-product-to-cart btn-themvaogio-custom"
                                            data-id="<?= $sanphamgoiy[$i]["id"] ?>"
                                            data-image="<?= $images ?>"
                                            data-name="<?= $sanphamgoiy[$i]["name_vi"] ?>"
                                            data-price_market="<?= intval($price_promotion) > 0 ? $price_promotion : $sanphamgoiy[$i]["price"] ; ?>"
                                            data-url="<?php echo $url; ?>"
                                            data-sku="<?php echo $sanphamgoiy[$i]["sku"]; ?>"
                                            data-kg="<?php echo $sanphamgoiy[$i]["kg"]; ?>"
                                            data-text_qt="<?= $sanphamgoiy[$i]["text_qt"] ? $sanphamgoiy[$i]["text_qt"] : '' ;?>"
                                            data-images_qt="<?= $images_qt ? $images_qt : '' ;?>"
                                    >Thêm vào giỏ</button>


                                </li>
                            </ul>
                        </div> -->
                    </div>

                    <?php }?>
            </div>
            </div>


        </div>
<?php }?>


</div>
<script>
    jQuery(document).ready(function(){initItemSliderProducts()});var initItemSliderProducts=function(){jQuery('.slide-pro').not('.slick-initialized').slick({autoplay:!1,dots:!1,infinite:!0,centerMode:!1,speed:300,slidesToShow:5,slidesToScroll:1,variableWidth:!1,autoplaySpeed:2000,nextArrow:'<span class="slick-next custom-ti"><i class="ti-angle-right"></i></span>',prevArrow:'<span class="slick-prev custom-ti"><i class="ti-angle-left"></i></span>',responsive:[{breakpoint:1024,settings:{slidesToShow:5,slidesToScroll:1,infinite:!0,dots:!1}},{breakpoint:600,settings:{slidesToShow:3,slidesToScroll:1}},{breakpoint:480,settings:{slidesToShow:1,slidesToScroll:1}}]})}
</script>